import { useEffect,useMemo,useState } from 'react';
import { api } from '../api/client';
import { Pagination } from '../components/Pagination';
export function AuditPage(){
  const[logs,setLogs]=useState<any[]>([]);const[error,setError]=useState('');const[query,setQuery]=useState('');const[action,setAction]=useState('');const[period,setPeriod]=useState('30');const[page,setPage]=useState(1);const[pageSize,setPageSize]=useState(25);
  useEffect(()=>{api.audit().then((r)=>setLogs(r.logs??[])).catch((e)=>setError(e instanceof Error?e.message:'Falha'));},[]);
  const actions=useMemo(()=>[...new Set(logs.map((log)=>String(log.action??'')).filter(Boolean))].sort(),[logs]);
  const filtered=useMemo(()=>{const raw=query.trim().toLocaleLowerCase('pt-BR');const cutoff=period==='all'?0:Date.now()-Number(period)*86_400_000;return logs.filter((log)=>{const hay=`${log.actorName??''} ${log.actorEmail??''} ${log.action??''} ${log.targetType??''} ${log.targetId??''} ${log.ipAddress??''}`.toLocaleLowerCase('pt-BR');const created=new Date(log.createdAt).getTime();return(!raw||hay.includes(raw))&&(!action||log.action===action)&&(!cutoff||created>=cutoff);});},[logs,query,action,period]);
  const totalPages=Math.max(1,Math.ceil(filtered.length/pageSize));useEffect(()=>setPage(1),[query,action,period,pageSize]);useEffect(()=>{if(page>totalPages)setPage(totalPages);},[page,totalPages]);const pageRows=useMemo(()=>filtered.slice((page-1)*pageSize,page*pageSize),[filtered,page,pageSize]);
  return <section><div className="page-heading"><span className="eyebrow">SEGURANÇA</span><h1>Auditoria administrativa</h1><p>Trilha de uso dos Masters e Analistas, com ação, alvo, data/hora, IP e navegador.</p></div>
  <div className="smart-toolbar"><div className="search-box grow"><span>⌕</span><input placeholder="Buscar usuário, ação, IP ou alvo" value={query} onChange={(e)=>setQuery(e.target.value)}/>{query&&<button className="search-clear" onClick={()=>setQuery('')} aria-label="Limpar busca">×</button>}</div><label className="inline-control">Ação<select value={action} onChange={(e)=>setAction(e.target.value)}><option value="">Todas</option>{actions.map((value)=><option key={value} value={value}>{value}</option>)}</select></label><label className="inline-control">Período<select value={period} onChange={(e)=>setPeriod(e.target.value)}><option value="7">7 dias</option><option value="30">30 dias</option><option value="90">90 dias</option><option value="all">Todo histórico</option></select></label></div>
  <div className="result-strip"><span><strong>{filtered.length}</strong> evento(s) encontrados</span><span className="push">Trilha somente leitura</span></div>{error&&<div className="form-error">{error}</div>}<div className="timeline audit-timeline">{pageRows.map((l)=><div key={l.id}><span className="timeline-dot"/><div className="audit-card"><div className="row-between"><strong>{l.actorName??'Sistema'} · {l.action}</strong><time>{new Date(l.createdAt).toLocaleString('pt-BR')}</time></div><p>{l.targetType??'—'} {l.targetId?`#${l.targetId}`:''}</p><div className="audit-meta"><span>IP: {l.ipAddress??'—'}</span><span>{l.actorEmail??''}</span></div>{l.metadata&&<details><summary>Metadados</summary><pre>{JSON.stringify(l.metadata,null,2)}</pre></details>}</div></div>)}</div>{pageRows.length===0&&<div className="empty-state panel">Nenhum log encontrado para os filtros.</div>}<Pagination page={page} pageSize={pageSize} total={filtered.length} onPageChange={setPage} onPageSizeChange={setPageSize} label="eventos"/></section>;
}
