import { useEffect,useMemo,useState } from 'react';
import { api } from '../api/client';
import { Modal } from '../components/Modal';
import { StatusBadge } from '../components/StatusBadge';
import { PayrollSearchModal, type PayrollSearchInput } from '../components/PayrollSearchModal';

function cpfMask(value:string){const d=value.replace(/\D/g,'').slice(0,11);return d.replace(/^(\d{3})(\d)/,'$1.$2').replace(/^(\d{3})\.(\d{3})(\d)/,'$1.$2.$3').replace(/\.(\d{3})(\d)/,'.$1-$2');}
function maskedCpf(cpf:string){const d=cpf.replace(/\D/g,'');return d.length===11?`${d.slice(0,3)}.${d.slice(3,6)}.${d.slice(6,9)}-${d.slice(9)}`:cpf;}
export function EmployeesPage(){const[employees,setEmployees]=useState<any[]>([]);const[groups,setGroups]=useState<any[]>([]);const[search,setSearch]=useState('');const[loading,setLoading]=useState(true);const[error,setError]=useState('');const[showNew,setShowNew]=useState(false);const[selected,setSelected]=useState<any|null>(null);
  async function load(){setLoading(true);try{const[e,g]=await Promise.all([api.employees(search),api.groups()]);setEmployees(e.employees);setGroups(g.groups);setError('');}catch(e){setError(e instanceof Error?e.message:'Falha ao carregar funcionários.');}finally{setLoading(false);}}useEffect(()=>{void load();},[]);
  return <section><div className="page-heading row-between"><div><span className="eyebrow">PESSOAS</span><h1>Funcionários</h1><p>Somente funcionários validados no Sage podem ser cadastrados e receber holerites.</p></div><button className="primary-button compact" onClick={()=>setShowNew(true)}>+ Novo funcionário</button></div><div className="toolbar"><div className="search-box"><span>⌕</span><input placeholder="Buscar por nome, CPF ou matrícula Sage" value={search} onChange={(e)=>setSearch(e.target.value)} onKeyDown={(e)=>{if(e.key==='Enter')void load();}}/><button onClick={()=>void load()}>Buscar</button></div><div className="toolbar-stat"><strong>{employees.length}</strong><span>resultados</span></div></div>{error&&<div className="form-error">{error}</div>}<div className="table-card"><table><thead><tr><th>Funcionário</th><th>CPF</th><th>Matrícula Sage</th><th>Grupo</th><th>Acesso</th><th>Status</th><th></th></tr></thead><tbody>{loading?<tr><td colSpan={7}><div className="empty-state">Carregando…</div></td></tr>:employees.length===0?<tr><td colSpan={7}><div className="empty-state">Nenhum funcionário cadastrado.</div></td></tr>:employees.map((e)=><tr key={e.id}><td><div className="person-cell"><div className="avatar soft">{String(e.name).slice(0,2).toUpperCase()}</div><div><strong>{e.name}</strong><span>{e.jobTitle??'Cargo não informado'}</span></div></div></td><td>{maskedCpf(e.cpf)}</td><td>{e.sageEmployeeCode}</td><td><span className="chip">{e.groupName}</span></td><td><StatusBadge status={e.accessStatus}/></td><td><StatusBadge status={e.status}/></td><td><button className="link-button" onClick={()=>setSelected(e)}>Abrir</button></td></tr>)}</tbody></table></div>{showNew&&<NewEmployeeModal groups={groups} onClose={()=>setShowNew(false)} onSaved={async()=>{setShowNew(false);await load();}}/>}{selected&&<EmployeeModal employeeId={selected.id} groups={groups} onClose={()=>setSelected(null)} onChanged={async()=>{await load();}}/>}</section>}

function NewEmployeeModal({groups,onClose,onSaved}:{groups:any[];onClose():void;onSaved():Promise<void>}){const[cpf,setCpf]=useState('');const[jobId,setJobId]=useState<number|null>(null);const[result,setResult]=useState<any|null>(null);const[state,setState]=useState<'idle'|'searching'|'found'|'not-found'>('idle');const[groupId,setGroupId]=useState('');const[error,setError]=useState('');const[saving,setSaving]=useState(false);const digits=useMemo(()=>cpf.replace(/\D/g,''),[cpf]);
  useEffect(()=>{if(digits.length!==11){setState('idle');setResult(null);setJobId(null);return;}let cancelled=false;const run=async()=>{setState('searching');setError('');try{const started=await api.employeeLookup(digits);if(cancelled)return;setJobId(started.jobId);for(let i=0;i<30&&!cancelled;i++){await new Promise((r)=>setTimeout(r,1500));const r=await api.employeeLookupResult(started.jobId);if(r.status==='FOUND'){setResult(r.employee);setState('found');return;}if(r.status==='NOT_FOUND'||r.status==='FAILED'){setState('not-found');setError(r.message??'Funcionário não encontrado no Sage.');return;}}if(!cancelled){setState('not-found');setError('A consulta demorou mais do que o esperado. Verifique o conector Sage.');}}catch(e){if(!cancelled){setState('not-found');setError(e instanceof Error?e.message:'Falha ao consultar Sage.');}}};void run();return()=>{cancelled=true};},[digits]);
  async function save(){if(!jobId||!groupId)return;setSaving(true);setError('');try{await api.createEmployee(jobId,Number(groupId));await onSaved();}catch(e){setError(e instanceof Error?e.message:'Falha ao cadastrar.');}finally{setSaving(false);}}
  return <Modal title="Cadastrar funcionário" onClose={onClose}><div className="form-grid two"><label>Empresa<input value="1" disabled/><span className="field-hint">Empresa fixa do Sage</span></label><label>CPF<input inputMode="numeric" placeholder="000.000.000-00" value={cpf} onChange={(e)=>setCpf(cpfMask(e.target.value))}/><span className="field-hint">A busca inicia automaticamente com 11 dígitos.</span></label></div>{state==='searching'&&<div className="lookup-card loading"><div className="spinner"/><div><strong>Consultando o Sage…</strong><span>Localizando funcionário pelo CPF na empresa 1.</span></div></div>}{state==='found'&&result&&<div className="lookup-card success"><div className="checkmark">✓</div><div className="grow"><span className="eyebrow">FUNCIONÁRIO LOCALIZADO</span><h3>{result.name}</h3><div className="lookup-data"><span><b>Matrícula</b>{result.sageEmployeeCode}</span><span><b>CPF</b>{cpfMask(result.cpf)}</span><span><b>Nascimento</b>{new Date(result.birthDate+'T12:00:00').toLocaleDateString('pt-BR')}</span><span><b>Admissão</b>{result.admissionDate?new Date(result.admissionDate+'T12:00:00').toLocaleDateString('pt-BR'):'—'}</span><span><b>Cargo</b>{result.jobTitle??'—'}</span><span><b>Situação Sage</b>{result.status??'—'}</span></div></div></div>}{state==='not-found'&&<div className="lookup-card danger"><strong>Cadastro bloqueado</strong><span>{error||'Funcionário não encontrado no Sage.'}</span></div>}{state==='found'&&<label>Grupo do funcionário<select value={groupId} onChange={(e)=>setGroupId(e.target.value)}><option value="">Selecione…</option>{groups.filter((g)=>g.status==='ACTIVE').map((g)=><option key={g.id} value={g.id}>{g.name}</option>)}</select></label>}{error&&state!=='not-found'&&<div className="form-error">{error}</div>}<div className="modal-actions"><button className="secondary-button" onClick={onClose}>Cancelar</button><button className="primary-button" disabled={state!=='found'||!groupId||saving} onClick={()=>void save()}>{saving?'Cadastrando…':'Confirmar cadastro'}</button></div></Modal>}

function EmployeeModal({employeeId,groups,onClose,onChanged}:{employeeId:number;groups:any[];onClose():void;onChanged():Promise<void>}){
  const[data,setData]=useState<any|null>(null);const[payrolls,setPayrolls]=useState<any[]>([]);const[error,setError]=useState('');const[busy,setBusy]=useState(false);const[showSearch,setShowSearch]=useState(false);
  async function load(){try{const[e,p]=await Promise.all([api.employee(employeeId),api.payrolls({employeeId})]);setData(e.employee);setPayrolls(p.payrolls);}catch(e){setError(e instanceof Error?e.message:'Falha ao carregar funcionário.');}}
  useEffect(()=>{void load();},[employeeId]);
  if(!data)return <Modal title="Funcionário" onClose={onClose}><div className="empty-state">Carregando…</div></Modal>;
  async function groupChange(groupId:number){setBusy(true);try{await api.moveEmployee(employeeId,groupId);await load();await onChanged();}catch(e){setError(e instanceof Error?e.message:'Falha ao alterar grupo.');}finally{setBusy(false);}}
  async function searchNow(input:PayrollSearchInput){const result=await api.searchEmployeeNow(employeeId,input);setError(`Busca ${String(input.month).padStart(2,'0')}/${input.year} enfileirada: execução #${result.runId}, job #${result.jobId}.`);}
  const group=groups.find((g)=>Number(g.id)===Number(data.group_id));
  return <>
    <Modal title={data.name} onClose={onClose} wide>
      <div className="profile-head"><div className="avatar xl">{String(data.name).slice(0,2).toUpperCase()}</div><div><h2>{data.name}</h2><p>CPF {maskedCpf(data.cpf)} · Matrícula Sage {data.sage_employee_code}</p><StatusBadge status={data.status}/></div><button className="primary-button compact push" disabled={busy} onClick={()=>setShowSearch(true)}>Buscar holerites agora</button></div>
      {error&&<div className={error.startsWith('Busca ')&&error.includes('enfileirada')?'success-note':'form-error'}>{error}</div>}
      <div className="detail-grid"><div><span>Empresa</span><strong>1</strong></div><div><span>Grupo</span><select disabled={busy} value={data.group_id} onChange={(e)=>void groupChange(Number(e.target.value))}>{groups.filter((g)=>g.status==='ACTIVE').map((g)=><option key={g.id} value={g.id}>{g.name}</option>)}</select></div><div><span>Admissão</span><strong>{data.admission_date?new Date(data.admission_date).toLocaleDateString('pt-BR'):'—'}</strong></div><div><span>Cargo</span><strong>{data.job_title??'—'}</strong></div><div><span>Acesso</span><strong>{data.hasPin?'PIN cadastrado':'Primeiro acesso pendente'}</strong></div><div><span>Último acesso</span><strong>{data.lastLoginAt?new Date(data.lastLoginAt).toLocaleString('pt-BR'):'Nunca'}</strong></div></div>
      <div className="section-title"><h3>Holerites</h3><span>{payrolls.length} documento(s)</span></div><div className="compact-list">{payrolls.length===0?<div className="empty-state">Nenhum holerite importado.</div>:payrolls.map((p)=><div className="compact-row" key={p.id}><div><strong>{String(p.month).padStart(2,'0')}/{p.year} · {p.payrollTypeLabel}</strong><span>Líquido: {p.netAmount==null?'—':Number(p.netAmount).toLocaleString('pt-BR',{style:'currency',currency:'BRL'})}</span></div><StatusBadge status={p.status}/></div>)}</div>
    </Modal>
    {showSearch&&<PayrollSearchModal title={`Buscar holerites · ${data.name}`} subtitle="Escolha a competência, o ano e um ou vários tipos para esta busca manual." defaultTypes={group?.payrollTypes??[2]} onClose={()=>setShowSearch(false)} onSubmit={searchNow}/>} 
  </>;
}
