import { useEffect,useState } from 'react';
import { api } from '../api/client';
import { Modal } from '../components/Modal';
import { StatusBadge } from '../components/StatusBadge';

const typeOptions=[{value:2,label:'2 — Mensal'},{value:3,label:'3 — Adiantamento 13º'},{value:4,label:'4 — 13º salário'},{value:6,label:'6 — Rescisão'}];
export function GroupsPage(){const[groups,setGroups]=useState<any[]>([]);const[editing,setEditing]=useState<any|null>(null);const[error,setError]=useState('');const[busy,setBusy]=useState<number|null>(null);async function load(){try{const r=await api.groups();setGroups(r.groups);setError('');}catch(e){setError(e instanceof Error?e.message:'Falha ao carregar grupos.');}}useEffect(()=>{void load();},[]);async function force(id:number){setBusy(id);try{const r=await api.searchGroupNow(id);setError(`Busca enfileirada: execução #${r.runId}, job #${r.jobId}.`);}catch(e){setError(e instanceof Error?e.message:'Falha ao iniciar busca.');}finally{setBusy(null);}}
  return <section><div className="page-heading row-between"><div><span className="eyebrow">AUTOMAÇÃO</span><h1>Grupos de funcionários</h1><p>Defina tipos de folha e vários horários de busca. As automações executam de segunda a sexta, sempre na competência atual.</p></div><button className="primary-button compact" onClick={()=>setEditing({new:true})}>+ Novo grupo</button></div>{error&&<div className={error.startsWith('Busca enfileirada')?'success-note':'form-error'}>{error}</div>}<div className="group-grid">{groups.map((g)=><article className="group-card" key={g.id}><header><div><span className="eyebrow">GRUPO</span><h3>{g.name}</h3></div><StatusBadge status={g.status}/></header><div className="group-kpis"><div><strong>{g.employeeCount}</strong><span>funcionários</span></div><div><strong>1</strong><span>empresa Sage</span></div><div><strong>{g.schedules?.length??0}</strong><span>horários</span></div></div><div className="group-section"><span className="label">Tipos de folha</span><div className="chip-list">{(g.payrollTypes??[]).map((t:number)=><span className="chip" key={t}>{typeOptions.find((o)=>o.value===t)?.label??t}</span>)}</div></div><div className="group-section"><span className="label">Busca automática · Segunda a sexta</span><div className="schedule-list">{g.schedules?.map((s:any)=><span key={s.id}>◷ {s.runTime}</span>)}</div></div><footer><button className="secondary-button compact" onClick={()=>setEditing(g)}>Configurar</button><button className="primary-button compact" disabled={busy===g.id} onClick={()=>void force(g.id)}>{busy===g.id?'Enfileirando…':'Buscar holerites agora'}</button></footer></article>)}</div>{groups.length===0&&<div className="empty-state panel">Nenhum grupo configurado.</div>}{editing&&<GroupModal group={editing.new?null:editing} onClose={()=>setEditing(null)} onSaved={async()=>{setEditing(null);await load();}}/>}</section>}

function GroupModal({group,onClose,onSaved}:{group:any|null;onClose():void;onSaved():Promise<void>}){const[name,setName]=useState(group?.name??'');const[types,setTypes]=useState<number[]>(group?.payrollTypes??[2]);const[times,setTimes]=useState<string[]>((group?.schedules??[]).map((s:any)=>s.runTime)??['00:00']);const[auto,setAuto]=useState(group?.autoSearchEnabled!==0);const[status,setStatus]=useState<'ACTIVE'|'DISABLED'>(group?.status??'ACTIVE');const[error,setError]=useState('');const[saving,setSaving]=useState(false);function toggleType(v:number){setTypes((current)=>current.includes(v)?current.filter((x)=>x!==v):[...current,v].sort());}function addTime(){setTimes((v)=>[...v,'12:00']);}async function save(){setSaving(true);setError('');try{const body={name,payrollTypes:types,times,autoSearchEnabled:auto,status};if(group)await api.updateGroup(group.id,body);else await api.createGroup(body);await onSaved();}catch(e){setError(e instanceof Error?e.message:'Falha ao salvar grupo.');}finally{setSaving(false);}}
  return <Modal title={group?'Configurar grupo':'Novo grupo'} onClose={onClose}><div className="form-grid two"><label>Nome do grupo<input value={name} onChange={(e)=>setName(e.target.value)} placeholder="Ex.: Administrativo"/></label><label>Empresa Sage<input value="1" disabled/><span className="field-hint">Fixa e não editável</span></label></div><div className="form-section"><span className="label strong">Tipos de folha consultados</span><div className="check-grid">{typeOptions.map((o)=><label className="check-card" key={o.value}><input type="checkbox" checked={types.includes(o.value)} onChange={()=>toggleType(o.value)}/><span>{o.label}</span></label>)}</div></div><div className="form-section"><div className="row-between"><div><span className="label strong">Horários automáticos</span><p className="muted small">Executados de segunda a sexta, no mês atual.</p></div><button className="secondary-button compact" onClick={addTime}>+ Horário</button></div><div className="time-grid">{times.map((time,i)=><div className="time-row" key={i}><input type="time" value={time} onChange={(e)=>setTimes((current)=>current.map((v,j)=>j===i?e.target.value:v))}/><button className="icon-button danger-text" onClick={()=>setTimes((current)=>current.filter((_,j)=>j!==i))}>×</button></div>)}</div></div><div className="form-grid two"><label className="switch-row"><input type="checkbox" checked={auto} onChange={(e)=>setAuto(e.target.checked)}/><span><strong>Busca automática</strong><small>Executar os horários deste grupo</small></span></label>{group&&<label>Status<select value={status} onChange={(e)=>setStatus(e.target.value as any)}><option value="ACTIVE">Ativo</option><option value="DISABLED">Desabilitado</option></select></label>}</div>{error&&<div className="form-error">{error}</div>}<div className="modal-actions"><button className="secondary-button" onClick={onClose}>Cancelar</button><button className="primary-button" disabled={saving||!name||types.length===0||times.length===0} onClick={()=>void save()}>{saving?'Salvando…':'Salvar grupo'}</button></div></Modal>}
