import { useEffect,useMemo,useState } from 'react';
import { api } from '../api/client';
import { useAuth } from '../auth/AuthProvider';
import { Modal } from '../components/Modal';
import { Pagination } from '../components/Pagination';
import { StatusBadge } from '../components/StatusBadge';
import { WorkerHealth } from '../components/WorkerHealth';

export function SageIntegrationPage(){
  const{principal}=useAuth();const[connectors,setConnectors]=useState<any[]>([]);const[jobs,setJobs]=useState<any[]>([]);const[dashboard,setDashboard]=useState<any>(null);const[logs,setLogs]=useState<any[]|null>(null);const[selectedJob,setSelectedJob]=useState<any|null>(null);const[token,setToken]=useState<any|null>(null);const[error,setError]=useState('');const[busy,setBusy]=useState('');const[query,setQuery]=useState('');const[typeFilter,setTypeFilter]=useState('');const[statusFilter,setStatusFilter]=useState('');const[page,setPage]=useState(1);const[pageSize,setPageSize]=useState(25);
  async function load(){try{const[c,j,d]=await Promise.all([api.connectors(),api.jobs(),api.dashboard()]);setConnectors(c.connectors??[]);setJobs(j.jobs??[]);setDashboard(d);setError('');}catch(e){setError(e instanceof Error?e.message:'Falha ao carregar integração.');}}
  useEffect(()=>{void load();const id=setInterval(()=>void load(),10000);return()=>clearInterval(id);},[]);
  async function diagnostic(type:'CONNECTION_TEST'|'SCHEMA_DISCOVERY'){setBusy(type);try{await api.createJob(type);await load();}catch(e){setError(e instanceof Error?e.message:'Falha ao enfileirar.');}finally{setBusy('');}}
  async function openLogs(job:any){try{const r=await api.jobLogs(job.id);setSelectedJob(job);setLogs(r.logs);}catch(e){setError(e instanceof Error?e.message:'Falha ao abrir logs.');}}
  const filtered=useMemo(()=>jobs.filter((job)=>{const raw=query.trim().toLocaleLowerCase('pt-BR');const display=jobDisplayStatus(job);const hay=`${job.id} ${label(job.jobType)} ${job.progressMessage??''} ${job.normalizationError??''} ${job.errorMessage??''}`.toLocaleLowerCase('pt-BR');return(!raw||hay.includes(raw))&&(!typeFilter||job.jobType===typeFilter)&&(!statusFilter||display===statusFilter);}),[jobs,query,typeFilter,statusFilter]);
  const totalPages=Math.max(1,Math.ceil(filtered.length/pageSize));useEffect(()=>setPage(1),[query,typeFilter,statusFilter,pageSize]);useEffect(()=>{if(page>totalPages)setPage(totalPages);},[page,totalPages]);const pageRows=useMemo(()=>filtered.slice((page-1)*pageSize,page*pageSize),[filtered,page,pageSize]);
  return <section><div className="page-heading row-between"><div><span className="eyebrow">DIAGNÓSTICO TÉCNICO</span><h1>Integração Sage</h1><p>Saúde do conector, testes controlados e histórico técnico com filtros para diagnóstico mais rápido.</p></div><button className="secondary-button compact" onClick={()=>void load()}>↻ Atualizar agora</button></div>{error&&<div className="form-error">{error}</div>}<WorkerHealth health={dashboard?.workerHealth}/>
  <div className="integration-grid"><div className="panel"><div className="panel-head"><div><span className="eyebrow">WINDOWS SERVICE</span><h3>Conectores</h3></div>{principal?.kind==='USER'&&principal.role==='MASTER'&&<button className="secondary-button compact" onClick={async()=>{const name=prompt('Nome do conector:','Sage Produção');if(!name)return;try{const r=await api.createConnector(name);setToken(r);await load();}catch(e){setError(e instanceof Error?e.message:'Falha');}}}>+ Conector</button>}</div><div className="connector-list">{connectors.map((c)=><div className="connector-row" key={c.id}><div className="connector-icon">↔</div><div className="grow"><strong>#{c.id} · {c.name}</strong><span>{c.machineName??'Aguardando serviço'} · {c.lastSeenAt?new Date(c.lastSeenAt).toLocaleString('pt-BR'):'sem heartbeat'}</span></div><StatusBadge status={c.status}/></div>)}</div></div><div className="panel"><span className="eyebrow">AÇÕES</span><h3>Testes controlados</h3><p className="muted">Não criam holerites. Servem somente para validar o SQL Server e o schema permitido.</p><div className="button-stack"><button className="primary-button" disabled={!!busy} onClick={()=>void diagnostic('CONNECTION_TEST')}>{busy==='CONNECTION_TEST'?'Enfileirando…':'Testar conexão'}</button><button className="secondary-button" disabled={!!busy} onClick={()=>void diagnostic('SCHEMA_DISCOVERY')}>{busy==='SCHEMA_DISCOVERY'?'Enfileirando…':'Descobrir schema'}</button></div></div></div>
  <div className="section-title"><div><span className="eyebrow">FILA</span><h3>Jobs recentes</h3></div></div><div className="smart-toolbar"><div className="search-box grow"><span>⌕</span><input placeholder="Buscar job, mensagem ou erro" value={query} onChange={(e)=>setQuery(e.target.value)}/>{query&&<button className="search-clear" onClick={()=>setQuery('')} aria-label="Limpar busca">×</button>}</div><label className="inline-control">Operação<select value={typeFilter} onChange={(e)=>setTypeFilter(e.target.value)}><option value="">Todas</option><option value="PAYROLL_IMPORT">Importação de folha</option><option value="EMPLOYEE_LOOKUP_BY_CPF">Busca por CPF</option><option value="CONNECTION_TEST">Teste de conexão</option><option value="SCHEMA_DISCOVERY">Descoberta do schema</option></select></label><label className="inline-control">Status<select value={statusFilter} onChange={(e)=>setStatusFilter(e.target.value)}><option value="">Todos</option><option value="COLLECTING">Coletando</option><option value="AWAITING_PROCESSING">Aguardando processamento</option><option value="GENERATING">Gerando</option><option value="COMPLETED">Concluído</option><option value="COLLECTION_FAILED">Falha na coleta</option><option value="GENERATION_FAILED">Falha ao gerar</option></select></label></div>
  <div className="table-card table-card-paged"><table><thead><tr><th>ID</th><th>Operação</th><th>Status</th><th>Progresso</th><th>Mensagem</th><th>Criado</th><th></th></tr></thead><tbody>{pageRows.length===0?<tr><td colSpan={7}><div className="empty-state">Nenhum job encontrado para os filtros.</div></td></tr>:pageRows.map((j)=><tr key={j.id}><td>#{j.id}</td><td><strong>{label(j.jobType)}</strong></td><td><StatusBadge status={jobDisplayStatus(j)}/></td><td><div className="progress-wrap"><div className="progress"><i style={{width:`${j.progressTotal?Math.round(j.progressCurrent/j.progressTotal*100):0}%`}}/></div><span>{j.progressCurrent}/{j.progressTotal}</span></div></td><td className="message-cell">{j.normalizationError??j.progressMessage??j.errorMessage??'—'}</td><td>{new Date(j.createdAt).toLocaleString('pt-BR')}</td><td><button className="link-button" onClick={()=>void openLogs(j)}>Logs</button></td></tr>)}</tbody></table></div><Pagination page={page} pageSize={pageSize} total={filtered.length} onPageChange={setPage} onPageSizeChange={setPageSize} label="jobs"/>
  {logs&&selectedJob&&<Modal title={`Logs · Job #${selectedJob.id}`} onClose={()=>{setLogs(null);setSelectedJob(null);}} wide><div className="log-list">{logs.length===0?<div className="empty-state">Sem logs.</div>:logs.map((l)=><div className={`log-row ${String(l.level).toLowerCase()}`} key={l.key??`${l.source??'log'}-${l.id}`}><StatusBadge status={l.level==='ERROR'?'ERROR':l.level}/><div className="grow"><strong>{l.message}</strong><span>{l.stage??'SAGE'} · {l.source==='PAYHUB'?'PayHub':'Conector Sage'}</span></div><time>{new Date(l.createdAt).toLocaleString('pt-BR')}</time></div>)}</div></Modal>}{token&&<Modal title="Token do conector" onClose={()=>setToken(null)}><div className="warning-note"><strong>Copie agora.</strong> Este token é mostrado somente nesta criação. Não envie por chat nem salve no Git.</div><label>Connector ID<input readOnly value={token.id}/></label><label>Token<input readOnly value={token.token} onFocus={(e)=>e.currentTarget.select()}/></label><button className="primary-button" onClick={()=>void navigator.clipboard.writeText(token.token)}>Copiar token</button></Modal>}</section>;
}
function label(type:string){return({CONNECTION_TEST:'Teste de conexão',SCHEMA_DISCOVERY:'Descoberta do schema',PAYROLL_IMPORT:'Importação de folha',EMPLOYEE_LOOKUP_BY_CPF:'Busca de funcionário por CPF'} as Record<string,string>)[type]??type}

function jobDisplayStatus(job:any){if(job.status==='FAILED')return 'COLLECTION_FAILED';if(job.jobType!=='PAYROLL_IMPORT')return job.status;if(job.normalizationState==='FAILED')return 'GENERATION_FAILED';if(job.normalizationState==='COMPLETED'||job.normalizedAt)return 'COMPLETED';if(job.normalizationState==='CLAIMED')return 'GENERATING';if(job.status==='COMPLETED'&&(job.normalizationState==='PENDING'||!job.normalizationState))return 'AWAITING_PROCESSING';if(job.status==='RUNNING')return 'COLLECTING';return job.status;}
