import { useEffect,useMemo,useState } from 'react';
import { api } from '../api/client';
import { Modal } from '../components/Modal';
import { Pagination } from '../components/Pagination';
import { StatusBadge } from '../components/StatusBadge';

export function UsersPage(){
  const[users,setUsers]=useState<any[]>([]);const[show,setShow]=useState(false);const[error,setError]=useState('');const[query,setQuery]=useState('');const[role,setRole]=useState('');const[status,setStatus]=useState('');const[page,setPage]=useState(1);const[pageSize,setPageSize]=useState(25);
  async function load(){try{const r=await api.users();setUsers(r.users??[]);setError('');}catch(e){setError(e instanceof Error?e.message:'Falha ao carregar usuários.');}}
  useEffect(()=>{void load();},[]);
  const filtered=useMemo(()=>users.filter((user)=>{const raw=query.trim().toLocaleLowerCase('pt-BR');return(!raw||String(user.name??'').toLocaleLowerCase('pt-BR').includes(raw)||String(user.email??'').toLocaleLowerCase('pt-BR').includes(raw))&&(!role||user.role===role)&&(!status||user.status===status);}),[users,query,role,status]);
  const totalPages=Math.max(1,Math.ceil(filtered.length/pageSize));useEffect(()=>{setPage(1);},[query,role,status,pageSize]);useEffect(()=>{if(page>totalPages)setPage(totalPages);},[page,totalPages]);const pageRows=useMemo(()=>filtered.slice((page-1)*pageSize,page*pageSize),[filtered,page,pageSize]);
  return <section><div className="page-heading row-between"><div><span className="eyebrow">ADMINISTRAÇÃO</span><h1>Usuários administrativos</h1><p>Gerencie Masters e Analistas. Analistas operam funcionários, grupos e holerites; segurança e auditoria permanecem com o Master.</p></div><button className="primary-button compact" onClick={()=>setShow(true)}>+ Novo Analista</button></div>
  <div className="smart-toolbar"><div className="search-box grow"><span>⌕</span><input placeholder="Buscar nome ou e-mail" value={query} onChange={(e)=>setQuery(e.target.value)}/>{query&&<button className="search-clear" onClick={()=>setQuery('')} aria-label="Limpar busca">×</button>}</div><label className="inline-control">Perfil<select value={role} onChange={(e)=>setRole(e.target.value)}><option value="">Todos</option><option value="MASTER">Master</option><option value="ANALISTA">Analista</option></select></label><label className="inline-control">Status<select value={status} onChange={(e)=>setStatus(e.target.value)}><option value="">Todos</option><option value="ACTIVE">Ativos</option><option value="DISABLED">Desabilitados</option></select></label></div>
  {error&&<div className="form-error">{error}</div>}<div className="table-card table-card-paged"><table><thead><tr><th>Nome</th><th>E-mail</th><th>Perfil</th><th>Status</th><th>Criado em</th><th></th></tr></thead><tbody>{pageRows.length===0?<tr><td colSpan={6}><div className="empty-state">Nenhum usuário encontrado.</div></td></tr>:pageRows.map((u)=><tr key={u.id}><td><strong>{u.name}</strong></td><td>{u.email}</td><td><span className="chip">{u.role}</span></td><td><StatusBadge status={u.status}/></td><td>{new Date(u.createdAt).toLocaleString('pt-BR')}</td><td>{u.role==='ANALISTA'&&<button className="link-button" onClick={async()=>{try{await api.setUserStatus(u.id,u.status==='ACTIVE'?'DISABLED':'ACTIVE');await load();}catch(e){setError(e instanceof Error?e.message:'Falha');}}}>{u.status==='ACTIVE'?'Desabilitar':'Ativar'}</button>}</td></tr>)}</tbody></table></div><Pagination page={page} pageSize={pageSize} total={filtered.length} onPageChange={setPage} onPageSizeChange={setPageSize} label="usuários"/>{show&&<NewAnalyst onClose={()=>setShow(false)} onSaved={async()=>{setShow(false);await load();}}/>}</section>;
}

function NewAnalyst({onClose,onSaved}:{onClose():void;onSaved():Promise<void>}){const[form,setForm]=useState({name:'',email:'',password:''});const[error,setError]=useState('');const[saving,setSaving]=useState(false);async function save(){setSaving(true);try{await api.createAnalyst(form);await onSaved();}catch(e){setError(e instanceof Error?e.message:'Falha ao criar Analista.');}finally{setSaving(false);}}return <Modal title="Novo Analista" onClose={onClose}><label>Nome completo<input value={form.name} onChange={(e)=>setForm({...form,name:e.target.value})}/></label><label>E-mail<input type="email" value={form.email} onChange={(e)=>setForm({...form,email:e.target.value})}/></label><label>Senha inicial<input type="password" minLength={10} value={form.password} onChange={(e)=>setForm({...form,password:e.target.value})}/><span className="field-hint">Mínimo de 10 caracteres.</span></label>{error&&<div className="form-error">{error}</div>}<div className="modal-actions"><button className="secondary-button" onClick={onClose}>Cancelar</button><button className="primary-button" disabled={saving||!form.name||!form.email||form.password.length<10} onClick={()=>void save()}>{saving?'Criando…':'Criar Analista'}</button></div></Modal>}
