import type { Pool, RowDataPacket } from 'mysql2/promise';
import { badRequest } from '../core/errors.js';
import type { RequestMeta, SignatureMode } from '../core/types.js';
import { AuditService } from './audit.service.js';

export interface AppSettings{signatureMode:SignatureMode;signatureLinkTtlMinutes:number;acceptanceText:string;updatedAt:Date|null;}
export class SettingsService{
  constructor(private pool:Pool,private audit:AuditService){}
  async get(companyId:number):Promise<AppSettings>{const [rows]=await this.pool.query<RowDataPacket[]>(`SELECT signature_mode signatureMode,signature_link_ttl_minutes signatureLinkTtlMinutes,acceptance_text acceptanceText,updated_at updatedAt FROM app_settings WHERE company_id=? LIMIT 1`,[companyId]);const row=rows[0];if(!row)return{signatureMode:'ACCEPT_AND_DRAW',signatureLinkTtlMinutes:1440,acceptanceText:'Declaro que visualizei o holerite, conferi seu conteúdo e manifesto eletronicamente minha ciência e recebimento.',updatedAt:null};return{signatureMode:row.signatureMode,signatureLinkTtlMinutes:Number(row.signatureLinkTtlMinutes),acceptanceText:String(row.acceptanceText),updatedAt:row.updatedAt??null};}
  async update(companyId:number,actorId:number,input:{signatureMode:SignatureMode;signatureLinkTtlMinutes:number;acceptanceText:string},meta:RequestMeta):Promise<void>{if(!['ACCEPT','ACCEPT_AND_DRAW'].includes(input.signatureMode))throw badRequest('Modo de assinatura inválido.');if(!Number.isInteger(input.signatureLinkTtlMinutes)||input.signatureLinkTtlMinutes<5||input.signatureLinkTtlMinutes>43200)throw badRequest('Validade do link deve estar entre 5 minutos e 30 dias.');if(input.acceptanceText.trim().length<20)throw badRequest('Texto de aceite muito curto.');await this.pool.execute(`UPDATE app_settings SET signature_mode=?,signature_link_ttl_minutes=?,acceptance_text=?,updated_by_user_id=?,updated_at=UTC_TIMESTAMP() WHERE company_id=?`,[input.signatureMode,input.signatureLinkTtlMinutes,input.acceptanceText.trim(),actorId,companyId]);await this.audit.record({companyId,actorUserId:actorId,action:'SIGNATURE_SETTINGS_UPDATED',targetType:'SETTINGS',targetId:companyId,meta,metadata:{signatureMode:input.signatureMode,signatureLinkTtlMinutes:input.signatureLinkTtlMinutes}});}
}
