import { execFile } from 'node:child_process';
import { promisify } from 'node:util';
import type { Pool, ResultSetHeader, RowDataPacket } from 'mysql2/promise';
import type { Env } from '../config/env.js';
import { badRequest, notFound, unauthorized } from '../core/errors.js';
import { canonicalJson, parseJson } from '../core/json.js';
import { brTimestamp } from '../core/time.js';
import { hashSecret, hmacSha256, isSixDigitPin, normalizeCpf, randomToken, sha256, verifySecret } from '../core/security.js';
import type { RequestMeta, SignatureMode } from '../core/types.js';
import { buildEvidenceReceiptPdf, buildPayrollPdf } from './pdf.service.js';
import { StorageService } from './storage.service.js';
import { SettingsService } from './settings.service.js';
import { AuditService } from './audit.service.js';
import { NotificationService } from './notification.service.js';
import { normalizeClientSignatureEvidence, type ClientSignatureEvidenceInput } from './signature-client-evidence.js';
import { withSignatureEvidenceDisclosure, withoutSignatureEvidenceDisclosure } from './signature-disclosure.js';

const execFileAsync=promisify(execFile);


function sageSnapshotValue(raw:unknown,aliases:string[]):string|null{const snapshot=parseJson<Record<string,unknown>>(raw,{});const entries=new Map(Object.entries(snapshot).map(([k,v])=>[k.toLowerCase(),v]));for(const alias of aliases){const value=entries.get(alias.toLowerCase());if(value!==undefined&&value!==null&&String(value).trim()!=='')return String(value).trim();}return null;}
const cboAliases=['cbo','cd_cbo','nr_cbo','codigo_cbo','cbo_funcao','cd_cbo_funcao'];

interface SignContext{requestId:number;payrollId:number;employeeId:number;employeeName:string;cpf:string;sageCode:string;cbo:string|null;jobTitle:string|null;admissionDate:string|null;rawReference:Record<string,unknown>;year:number;month:number;payrollType:number;typeLabel:string;gross:number|null;deductions:number|null;net:number|null;status:string;acceptanceText:string;acceptanceHash:string;originalPath:string;originalHash:string;signatureMode:SignatureMode;}

export class SignatureService{
  constructor(private pool:Pool,private storage:StorageService,private settings:SettingsService,private audit:AuditService,private notifications:NotificationService,private env:Env){}

  private async contextByRequest(requestId:number):Promise<SignContext>{const cfg=await this.settings.get();const [rows]=await this.pool.execute<RowDataPacket[]>(`SELECT sr.id requestId,sr.payroll_id payrollId,sr.employee_id employeeId,sr.status requestStatus,sr.acceptance_text acceptanceText,sr.acceptance_text_hash acceptanceHash,p.status,p.year,p.month,p.payroll_type payrollType,p.payroll_type_label typeLabel,p.gross_amount gross,p.deduction_amount deductions,p.net_amount net,p.raw_reference_json rawReferenceJson,e.name employeeName,e.cpf,e.sage_employee_code sageCode,e.sage_snapshot_json sageSnapshotJson,e.job_title jobTitle,DATE_FORMAT(e.admission_date,'%Y-%m-%d') admissionDate,d.original_path originalPath,d.original_sha256 originalHash FROM signature_requests sr JOIN payrolls p ON p.id=sr.payroll_id JOIN employees e ON e.id=sr.employee_id JOIN payroll_documents d ON d.payroll_id=p.id WHERE sr.id=? LIMIT 1`,[requestId]);const r=rows[0];if(!r)throw notFound('Solicitação de assinatura não encontrada.');const acceptanceText=withSignatureEvidenceDisclosure(String(r.acceptanceText));const acceptanceHash=sha256(acceptanceText);return{requestId:Number(r.requestId),payrollId:Number(r.payrollId),employeeId:Number(r.employeeId),employeeName:String(r.employeeName),cpf:String(r.cpf),sageCode:String(r.sageCode),cbo:sageSnapshotValue(r.sageSnapshotJson,cboAliases),jobTitle:r.jobTitle?String(r.jobTitle):null,admissionDate:r.admissionDate?String(r.admissionDate):null,rawReference:parseJson<Record<string,unknown>>(r.rawReferenceJson,{}),year:Number(r.year),month:Number(r.month),payrollType:Number(r.payrollType),typeLabel:String(r.typeLabel),gross:r.gross==null?null:Number(r.gross),deductions:r.deductions==null?null:Number(r.deductions),net:r.net==null?null:Number(r.net),status:String(r.status),acceptanceText,acceptanceHash,originalPath:String(r.originalPath),originalHash:String(r.originalHash),signatureMode:cfg.signatureMode};}

  private humanizeAuthMethod(method:string):string{return({PIN_VERIFIED:'PIN verificado',FIRST_ACCESS_VERIFIED:'Primeiro acesso validado'} as Record<string,string>)[method]??method;}
  private humanizeOrigin(origin:string):string{return({TEMPORARY_LINK:'Link temporário',PORTAL:'Portal',PWA:'PWA',ANDROID:'Android'} as Record<string,string>)[origin]??origin;}
  private humanizeLocation(location:Record<string,unknown>):string{const status=String(location.status??'UNSUPPORTED');const statusLabel=({CAPTURED:'Capturada',DENIED:'Negada pelo usuário',TIMEOUT:'Tempo esgotado',UNAVAILABLE:'Indisponível',UNSUPPORTED:'Não suportada',ERROR:'Erro ao capturar'} as Record<string,string>)[status]??status;const parts=[statusLabel];if(location.latitude!=null&&location.longitude!=null)parts.push(`${location.latitude}, ${location.longitude}`);if(location.accuracyMeters!=null)parts.push(`precisão ${location.accuracyMeters} m`);return parts.join(' | ');} 

  private async appendEvent(requestId:number,type:string,data:Record<string,unknown>):Promise<string>{const [rows]=await this.pool.execute<RowDataPacket[]>(`SELECT event_hash eventHash FROM signature_events WHERE signature_request_id=? ORDER BY id DESC LIMIT 1`,[requestId]);const previous=rows[0]?.eventHash?String(rows[0].eventHash):null;const eventJson=canonicalJson({type,data,at:new Date().toISOString()});const eventHash=sha256(`${previous??''}|${eventJson}`);await this.pool.execute(`INSERT INTO signature_events (signature_request_id,event_type,event_json,previous_hash,event_hash,created_at) VALUES (?,?,?,?,?,UTC_TIMESTAMP())`,[requestId,type,eventJson,previous,eventHash]);return eventHash;}

  async createLink(actorId:number,payrollId:number,meta:RequestMeta,ttlOverride?:number):Promise<{url:string;expiresAt:Date;token:string}>{
    const [rows]=await this.pool.execute<RowDataPacket[]>(`SELECT sr.id requestId,sr.status,p.status payrollStatus FROM signature_requests sr JOIN payrolls p ON p.id=sr.payroll_id WHERE sr.payroll_id=? LIMIT 1`,[payrollId]);const row=rows[0];if(!row)throw badRequest('Libere o holerite para assinatura antes de gerar o link.');if(row.status==='SIGNED'||row.payrollStatus==='SIGNED')throw badRequest('Holerite já assinado.');const cfg=await this.settings.get();const ttl=ttlOverride??cfg.signatureLinkTtlMinutes;if(ttl<5||ttl>43200)throw badRequest('Validade do link inválida.');const token=randomToken(36);const expires=new Date(Date.now()+ttl*60_000);const [insert]=await this.pool.execute<ResultSetHeader>(`INSERT INTO signature_links (signature_request_id,token_hash,created_by_user_id,created_at,expires_at,used_at,revoked_at) VALUES (?,?,?,UTC_TIMESTAMP(),?,NULL,NULL)`,[row.requestId,sha256(token),actorId,expires]);await this.appendEvent(Number(row.requestId),'LINK_CREATED',{linkId:insert.insertId,expiresAt:expires.toISOString(),createdByUserId:actorId});await this.audit.record({actorUserId:actorId,action:'SIGNATURE_LINK_CREATED',targetType:'PAYROLL',targetId:payrollId,meta,metadata:{linkId:insert.insertId,expiresAt:expires.toISOString()}});return{url:`${this.env.APP_ORIGIN}/#/sign/${token}`,expiresAt:expires,token};
  }

  private async resolveLink(token:string):Promise<{linkId:number;requestId:number;usedAt:Date|null;expiresAt:Date}>{const [rows]=await this.pool.execute<RowDataPacket[]>(`SELECT id linkId,signature_request_id requestId,used_at usedAt,expires_at expiresAt,revoked_at revokedAt FROM signature_links WHERE token_hash=? LIMIT 1`,[sha256(token)]);const row=rows[0];if(!row||row.revokedAt)throw notFound('Link de assinatura inválido.');if(new Date(row.expiresAt as string).getTime()<=Date.now())throw badRequest('Este link de assinatura expirou.','LINK_EXPIRED');return{linkId:Number(row.linkId),requestId:Number(row.requestId),usedAt:row.usedAt?new Date(row.usedAt as string):null,expiresAt:new Date(row.expiresAt as string)};}

  async publicInfo(token:string,meta:RequestMeta):Promise<Record<string,unknown>>{const link=await this.resolveLink(token);const ctx=await this.contextByRequest(link.requestId);const [cred]=await this.pool.execute<RowDataPacket[]>(`SELECT pin_hash pinHash FROM employee_credentials WHERE employee_id=? LIMIT 1`,[ctx.employeeId]);await this.appendEvent(ctx.requestId,'LINK_OPENED',{linkId:link.linkId,ip:meta.ipAddress,userAgent:meta.userAgent});return{requestId:ctx.requestId,payrollId:ctx.payrollId,employeeName:ctx.employeeName,cpfMasked:`***.***.***-${ctx.cpf.slice(-2)}`,competence:`${String(ctx.month).padStart(2,'0')}/${ctx.year}`,payrollTypeLabel:ctx.typeLabel,status:ctx.status,hasPin:Boolean(cred[0]?.pinHash),signatureMode:ctx.signatureMode,acceptanceText:ctx.acceptanceText,expiresAt:link.expiresAt,alreadyUsed:Boolean(link.usedAt)};}

  private async verifyExistingPin(employeeId:number,pin:string):Promise<void>{if(!isSixDigitPin(pin))throw unauthorized('PIN inválido.');const [rows]=await this.pool.execute<RowDataPacket[]>(`SELECT pin_hash pinHash,failed_attempts attempts,locked_until lockedUntil FROM employee_credentials WHERE employee_id=? LIMIT 1`,[employeeId]);const row=rows[0];if(!row?.pinHash)throw unauthorized('Primeiro acesso necessário.','PIN_NOT_SET');if(row.lockedUntil&&new Date(row.lockedUntil as string).getTime()>Date.now())throw unauthorized('Acesso temporariamente bloqueado.');if(!(await verifySecret(pin,String(row.pinHash)))){const attempts=Number(row.attempts??0)+1;const lock=attempts>=5?new Date(Date.now()+15*60_000):null;await this.pool.execute(`UPDATE employee_credentials SET failed_attempts=?,locked_until=?,updated_at=UTC_TIMESTAMP() WHERE employee_id=?`,[attempts,lock,employeeId]);throw unauthorized('PIN inválido.');}await this.pool.execute(`UPDATE employee_credentials SET failed_attempts=0,locked_until=NULL,updated_at=UTC_TIMESTAMP() WHERE employee_id=?`,[employeeId]);}

  private async activateFromLink(employeeId:number,cpfInput:string,birthDate:string,newPin:string):Promise<void>{const cpf=normalizeCpf(cpfInput);if(!isSixDigitPin(newPin))throw badRequest('O novo PIN deve possuir 6 números.');const [rows]=await this.pool.execute<RowDataPacket[]>(`SELECT cpf,DATE_FORMAT(birth_date,'%Y-%m-%d') birthDate FROM employees WHERE id=? LIMIT 1`,[employeeId]);const row=rows[0];if(!row||String(row.cpf)!==cpf||String(row.birthDate)!==birthDate)throw unauthorized('CPF ou data de nascimento não conferem.');const hash=await hashSecret(newPin);await this.pool.execute(`INSERT INTO employee_credentials (employee_id,pin_hash,activated_at,pin_changed_at,failed_attempts,locked_until,last_login_at,updated_at) VALUES (?,?,UTC_TIMESTAMP(),UTC_TIMESTAMP(),0,NULL,NULL,UTC_TIMESTAMP()) ON DUPLICATE KEY UPDATE pin_hash=VALUES(pin_hash),activated_at=COALESCE(activated_at,UTC_TIMESTAMP()),pin_changed_at=UTC_TIMESTAMP(),failed_attempts=0,locked_until=NULL,updated_at=UTC_TIMESTAMP()`,[employeeId,hash]);}

  async verifyLinkIdentity(token:string,input:{pin?:string;cpf?:string;birthDate?:string;newPin?:string},meta:RequestMeta):Promise<Record<string,unknown>>{
    const link=await this.resolveLink(token);if(link.usedAt)throw badRequest('Este link já foi utilizado.');const ctx=await this.contextByRequest(link.requestId);
    const [credRows]=await this.pool.execute<RowDataPacket[]>(`SELECT pin_hash pinHash FROM employee_credentials WHERE employee_id=? LIMIT 1`,[ctx.employeeId]);
    let authMethod:'PIN_VERIFIED'|'FIRST_ACCESS_VERIFIED';
    if(credRows[0]?.pinHash){if(!input.pin)throw unauthorized('Informe o PIN de 6 dígitos.');await this.verifyExistingPin(ctx.employeeId,input.pin);authMethod='PIN_VERIFIED';}
    else{if(!input.cpf||!input.birthDate||!input.newPin)throw badRequest('CPF, data de nascimento e novo PIN são obrigatórios no primeiro acesso.');await this.activateFromLink(ctx.employeeId,input.cpf,input.birthDate,input.newPin);authMethod='FIRST_ACCESS_VERIFIED';}
    await this.appendEvent(ctx.requestId,'IDENTITY_VERIFIED',{authMethod,origin:'TEMPORARY_LINK',ip:meta.ipAddress});
    await this.appendEvent(ctx.requestId,'DOCUMENT_VIEWED',{payrollId:ctx.payrollId,origin:'TEMPORARY_LINK'});
    const [items]=await this.pool.execute<RowDataPacket[]>(`SELECT event_code eventCode,description,reference_value referenceValue,amount,nature FROM payroll_items WHERE payroll_id=? ORDER BY sort_order,id`,[ctx.payrollId]);
    return{authMethod,payroll:{id:ctx.payrollId,employeeName:ctx.employeeName,sageCode:ctx.sageCode,cbo:ctx.cbo,jobTitle:ctx.jobTitle,admissionDate:ctx.admissionDate,month:ctx.month,year:ctx.year,competence:`${String(ctx.month).padStart(2,'0')}/${ctx.year}`,payrollTypeLabel:ctx.typeLabel,grossAmount:ctx.gross,deductionAmount:ctx.deductions,netAmount:ctx.net,rawReference:ctx.rawReference,items},acceptanceText:ctx.acceptanceText,signatureMode:ctx.signatureMode};
  }

  private async tsaStamp(evidenceHash:string):Promise<{storedValue:string|null;statusLabel:string;present:boolean}>{if(!this.env.TSA_URL)return{storedValue:null,statusLabel:'Não configurado.',present:false};try{const {stdout}=await execFileAsync('openssl',['ts','-query','-digest',evidenceHash,'-sha256','-cert'],{encoding:'buffer',maxBuffer:1024*1024});const headers:Record<string,string>={'content-type':'application/timestamp-query','accept':'application/timestamp-reply'};if(this.env.TSA_BEARER_TOKEN)headers.authorization=`Bearer ${this.env.TSA_BEARER_TOKEN}`;const response=await fetch(this.env.TSA_URL,{method:'POST',headers,body:new Uint8Array(stdout as Buffer)});if(!response.ok)throw new Error(`TSA HTTP ${response.status}`);const data=Buffer.from(await response.arrayBuffer());return{storedValue:data.toString('base64'),statusLabel:'Registrado com sucesso (TSA RFC 3161).',present:true};}catch(error){return{storedValue:JSON.stringify({error:error instanceof Error?error.message:String(error),at:new Date().toISOString()}),statusLabel:'Configurado, porém houve falha no registro externo.',present:false};}}

  private decodeDrawing(dataUrl:string|undefined):Buffer|null{if(!dataUrl)return null;const match=/^data:image\/png;base64,([A-Za-z0-9+/=]+)$/.exec(dataUrl);if(!match)throw badRequest('Assinatura desenhada inválida.');const buffer=Buffer.from(match[1]!,'base64');if(buffer.length<50||buffer.length>700_000)throw badRequest('Assinatura desenhada inválida ou muito grande.');return buffer;}

  private async performSign(ctx:SignContext,authMethod:'PIN_VERIFIED'|'FIRST_ACCESS_VERIFIED',origin:'PORTAL'|'PWA'|'ANDROID'|'TEMPORARY_LINK',meta:RequestMeta,drawingDataUrl?:string,sessionReference?:string,clientEvidenceInput?:ClientSignatureEvidenceInput):Promise<{evidenceId:number;signedAt:string}>{
    if(ctx.status==='SIGNED')throw badRequest('Este holerite já foi assinado.');const drawing=this.decodeDrawing(drawingDataUrl);if(ctx.signatureMode==='ACCEPT_AND_DRAW'&&!drawing)throw badRequest('A assinatura desenhada é obrigatória nesta configuração.');
    const signedAtDate=new Date();const signedAtBrt=brTimestamp(signedAtDate);let drawingStored:{path:string;sha256:string}|null=null;if(drawing)drawingStored=await this.storage.write(`signatures/${ctx.requestId}/drawing.png`,drawing);
    const clientEvidence=await normalizeClientSignatureEvidence(clientEvidenceInput,this.env);
    await this.appendEvent(ctx.requestId,'IDENTITY_VERIFIED',{authMethod,origin,ip:meta.ipAddress});await this.appendEvent(ctx.requestId,'DOCUMENT_VIEWED',{payrollId:ctx.payrollId});await this.appendEvent(ctx.requestId,'ACCEPTANCE_CONFIRMED',{acceptanceTextHash:ctx.acceptanceHash});await this.appendEvent(ctx.requestId,'CLIENT_EVIDENCE_CAPTURED',{origin,clientEvidence});
    const [itemRows]=await this.pool.execute<RowDataPacket[]>(`SELECT event_code code,description,reference_value referenceValue,amount,nature FROM payroll_items WHERE payroll_id=? ORDER BY sort_order,id`,[ctx.payrollId]);
    const base=(ctx.rawReference?.base??{}) as Record<string,unknown>;const pdfItems=itemRows.map((i)=>({code:String(i.code),description:String(i.description),reference:i.referenceValue?String(i.referenceValue):null,amount:Number(i.amount),nature:String(i.nature)}));const salaryBase=pdfItems.find((i)=>i.code==='1'&&i.nature==='EARNING')?.amount??null;const fgtsBase=base.vl_base_fgts==null?null:Number(base.vl_base_fgts);const signedPdf=buildPayrollPdf({title:'PayHub - Holerite Assinado Eletronicamente',employeeName:ctx.employeeName,cpfMasked:`***.***.***-${ctx.cpf.slice(-2)}`,sageCode:ctx.sageCode,competence:`${String(ctx.month).padStart(2,'0')}/${ctx.year}`,typeLabel:ctx.typeLabel,jobTitle:ctx.jobTitle,admissionDate:ctx.admissionDate,cbo:ctx.cbo,gross:ctx.gross,deductions:ctx.deductions,net:ctx.net,salaryBase,inssBase:base.vl_base_inss==null?null:Number(base.vl_base_inss),fgtsBase,fgtsMonth:fgtsBase==null?null:Math.round(fgtsBase*8)/100,irrfBase:base.vl_base_irrf==null?null:Number(base.vl_base_irrf),irrfBracket:0,items:pdfItems,signatureInfo:{signedAt:signedAtBrt,acceptanceText:withoutSignatureEvidenceDisclosure(ctx.acceptanceText)}});
    const signedStored=await this.storage.write(`payrolls/${ctx.employeeId}/${ctx.year}/${String(ctx.month).padStart(2,'0')}/${ctx.payrollType}/signed-${ctx.payrollId}.pdf`,signedPdf);
    const evidence={version:2,signatureRequestId:ctx.requestId,payrollId:ctx.payrollId,employeeId:ctx.employeeId,employeeCpf:ctx.cpf,sageEmployeeCode:ctx.sageCode,competence:{year:ctx.year,month:ctx.month},payrollType:ctx.payrollType,originalPdfSha256:ctx.originalHash,signedPdfSha256:signedStored.sha256,acceptanceText:ctx.acceptanceText,acceptanceTextHash:ctx.acceptanceHash,authMethod,origin,signedAtUtc:signedAtDate.toISOString(),signedAtBrt,ipAddress:meta.ipAddress,userAgent:meta.userAgent,sessionReference:sessionReference??null,drawingSha256:drawingStored?.sha256??null,clientEvidence,clientEvidenceSource:'CLIENT_REPORTED',serverEvidence:{ipAddress:meta.ipAddress,userAgent:meta.userAgent}};
    const evidenceJson=canonicalJson(evidence);const evidenceHash=sha256(evidenceJson);const seal=hmacSha256(this.env.SIGNATURE_SEAL_SECRET,evidenceJson);const tsa=await this.tsaStamp(evidenceHash);
    const device=(clientEvidence.device??{}) as Record<string,unknown>;const location=(clientEvidence.location??{}) as Record<string,unknown>;const receipt=buildEvidenceReceiptPdf({employeeName:ctx.employeeName,cpfMasked:`***.***.***-${ctx.cpf.slice(-2)}`,competence:`${String(ctx.month).padStart(2,'0')}/${ctx.year}`,typeLabel:ctx.typeLabel,signedAt:signedAtBrt,authMethod:this.humanizeAuthMethod(authMethod),origin:this.humanizeOrigin(origin),ipAddress:meta.ipAddress??'não informado',device:(`${device.type??'não disponível'} | ${device.brand??device.manufacturer??''} ${device.model??''}`).trim(),system:(`${device.osName??device.platform??'não disponível'} ${device.osVersion??device.platformVersion??''}`).trim(),browser:(`${device.browserName??'WebView/App'} ${device.browserVersion??device.appVersion??''}`).trim(),location:this.humanizeLocation(location),approximateAddress:String(location.address??'não disponível'),originalHash:ctx.originalHash,signedHash:signedStored.sha256,evidenceHash,hmacSeal:seal,tsaStatus:tsa.statusLabel});const receiptStored=await this.storage.write(`signatures/${ctx.requestId}/receipt.pdf`,receipt);
    const conn=await this.pool.getConnection();let evidenceId=0;try{await conn.beginTransaction();const [insert]=await conn.execute<ResultSetHeader>(`INSERT INTO signature_evidence (signature_request_id,payroll_id,employee_id,auth_method,origin,original_pdf_sha256,signed_pdf_sha256,acceptance_text_hash,evidence_json,evidence_sha256,seal_hmac_sha256,tsa_response,ip_address,user_agent,session_reference,drawing_path,drawing_sha256,signed_at_utc,signed_at_brt,created_at) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,UTC_TIMESTAMP(),?,UTC_TIMESTAMP())`,[ctx.requestId,ctx.payrollId,ctx.employeeId,authMethod,origin,ctx.originalHash,signedStored.sha256,ctx.acceptanceHash,evidenceJson,evidenceHash,seal,tsa.storedValue,meta.ipAddress,meta.userAgent,sessionReference??null,drawingStored?.path??null,drawingStored?.sha256??null,signedAtBrt]);evidenceId=insert.insertId;await conn.execute(`UPDATE payroll_documents SET signed_path=?,signed_sha256=?,receipt_path=?,receipt_sha256=?,updated_at=UTC_TIMESTAMP() WHERE payroll_id=?`,[signedStored.path,signedStored.sha256,receiptStored.path,receiptStored.sha256,ctx.payrollId]);await conn.execute(`UPDATE signature_requests SET status='SIGNED',signed_at=UTC_TIMESTAMP() WHERE id=?`,[ctx.requestId]);await conn.execute(`UPDATE payrolls SET status='SIGNED',signed_at=UTC_TIMESTAMP(),updated_at=UTC_TIMESTAMP() WHERE id=?`,[ctx.payrollId]);await conn.execute(`INSERT INTO document_access_logs (payroll_id,actor_type,actor_id,action,ip_address,user_agent,created_at) VALUES (?,?,?,?,?,?,UTC_TIMESTAMP())`,[ctx.payrollId,origin==='TEMPORARY_LINK'?'PUBLIC_LINK':'EMPLOYEE',ctx.employeeId,'SIGN',meta.ipAddress,meta.userAgent]);await conn.commit();}catch(e){await conn.rollback();throw e;}finally{conn.release();}
    await this.appendEvent(ctx.requestId,'SIGNATURE_CREATED',{evidenceId,signedPdfSha256:signedStored.sha256,evidenceSha256:evidenceHash});await this.appendEvent(ctx.requestId,'DOCUMENT_SEALED',{sealHmacSha256:seal,tsaPresent:tsa.present,tsaConfigured:Boolean(this.env.TSA_URL)});
    await this.notifications.notifyEmployee(ctx.employeeId,{category:'SIGNATURE_COMPLETED',title:'Assinatura registrada',body:`Seu holerite de ${String(ctx.month).padStart(2,'0')}/${ctx.year} foi assinado com sucesso.`,url:'/#/employee',dedupKey:`signature-completed:${ctx.payrollId}`});
    return{evidenceId,signedAt:signedAtBrt};
  }

  async signFromPortal(employeeId:number,payrollId:number,pin:string,drawing:string|undefined,origin:'PORTAL'|'PWA'|'ANDROID',meta:RequestMeta,sessionReference?:string,clientEvidence?:ClientSignatureEvidenceInput){const [rows]=await this.pool.execute<RowDataPacket[]>(`SELECT id FROM signature_requests WHERE payroll_id=? AND employee_id=? AND status='PENDING' LIMIT 1`,[payrollId,employeeId]);const row=rows[0];if(!row)throw notFound('Solicitação de assinatura não encontrada.');await this.verifyExistingPin(employeeId,pin);const ctx=await this.contextByRequest(Number(row.id));return this.performSign(ctx,'PIN_VERIFIED',origin,meta,drawing,sessionReference,clientEvidence);}

  async signFromLink(token:string,input:{pin?:string;cpf?:string;birthDate?:string;newPin?:string;drawing?:string;clientEvidence?:ClientSignatureEvidenceInput},meta:RequestMeta){const link=await this.resolveLink(token);if(link.usedAt)throw badRequest('Este link já foi utilizado.');const ctx=await this.contextByRequest(link.requestId);const [credRows]=await this.pool.execute<RowDataPacket[]>(`SELECT pin_hash pinHash FROM employee_credentials WHERE employee_id=? LIMIT 1`,[ctx.employeeId]);let auth:'PIN_VERIFIED'|'FIRST_ACCESS_VERIFIED';if(credRows[0]?.pinHash){if(!input.pin)throw unauthorized('Informe o PIN de 6 dígitos.');await this.verifyExistingPin(ctx.employeeId,input.pin);auth='PIN_VERIFIED';}else{if(!input.cpf||!input.birthDate||!input.newPin)throw badRequest('CPF, data de nascimento e novo PIN são obrigatórios no primeiro acesso.');await this.activateFromLink(ctx.employeeId,input.cpf,input.birthDate,input.newPin);auth='FIRST_ACCESS_VERIFIED';}const result=await this.performSign(ctx,auth,'TEMPORARY_LINK',meta,input.drawing,`signature-link:${link.linkId}`,input.clientEvidence);await this.pool.execute(`UPDATE signature_links SET used_at=UTC_TIMESTAMP() WHERE id=?`,[link.linkId]);return result;}

  async evidence(payrollId:number):Promise<Record<string,unknown>>{const [rows]=await this.pool.execute<RowDataPacket[]>(`SELECT se.*,sr.requested_at requestedAt,u.name requestedByName FROM signature_evidence se JOIN signature_requests sr ON sr.id=se.signature_request_id JOIN users u ON u.id=sr.requested_by_user_id WHERE se.payroll_id=? LIMIT 1`,[payrollId]);const row=rows[0];if(!row)throw notFound('Evidência de assinatura não encontrada.');const [events]=await this.pool.execute<RowDataPacket[]>(`SELECT id,event_type eventType,event_json eventJson,previous_hash previousHash,event_hash eventHash,created_at createdAt FROM signature_events WHERE signature_request_id=? ORDER BY id`,[row.signature_request_id]);const {drawing_path:_,evidence_json:__,...safe}=row as Record<string,unknown>;return{...safe,hasDrawing:Boolean(row.drawing_path),evidence:parseJson(row.evidence_json,{}),events:events.map((e)=>({...e,event:parseJson(e.eventJson,{}),eventJson:undefined}))};}

  async receipt(payrollId:number):Promise<{buffer:Buffer;filename:string;sha256:string}>{const [rows]=await this.pool.execute<RowDataPacket[]>(`SELECT receipt_path receiptPath,receipt_sha256 receiptSha256 FROM payroll_documents WHERE payroll_id=? LIMIT 1`,[payrollId]);const row=rows[0];if(!row?.receiptPath)throw notFound('Comprovante de evidências não encontrado.');const path=String(row.receiptPath);if(!(await this.storage.exists(path)))throw notFound('Arquivo do comprovante de evidências não encontrado.');return{buffer:await this.storage.read(path),filename:`comprovante-evidencias-holerite-${payrollId}.pdf`,sha256:String(row.receiptSha256??'')};}

  async drawing(payrollId:number):Promise<{buffer:Buffer;filename:string;sha256:string}>{const [rows]=await this.pool.execute<RowDataPacket[]>(`SELECT drawing_path drawingPath,drawing_sha256 drawingSha256 FROM signature_evidence WHERE payroll_id=? LIMIT 1`,[payrollId]);const row=rows[0];if(!row?.drawingPath)throw notFound('Assinatura desenhada não encontrada.');const path=String(row.drawingPath);if(!(await this.storage.exists(path)))throw notFound('Arquivo da assinatura desenhada não encontrado.');return{buffer:await this.storage.read(path),filename:`assinatura-holerite-${payrollId}.png`,sha256:String(row.drawingSha256??'')};}
}
