import {Router} from 'express';
import type {Pool,RowDataPacket} from 'mysql2/promise';
import type {Env} from '../config/env.js';
import {badRequest,notFound} from '../core/errors.js';
import {pontoCertoBridgeAuth} from '../middleware/ponto-certo-bridge.js';
import type {CompanyProvisioningService} from '../services/company-provisioning.service.js';
const val=(v:unknown)=>String(v??'').trim();
export function pontoCertoInternalRoutes(pool:Pool,env:Env,provisioning:CompanyProvisioningService){const r=Router();r.use(pontoCertoBridgeAuth(env));
 r.get('/companies',async(req,res)=>{const q=val(req.query.q);const args:any[]=[];let where='1=1';if(q){where+=' AND (c.legal_name LIKE ? OR c.display_name LIKE ? OR c.slug LIKE ?)';args.push(`%${q}%`,`%${q}%`,`%${q}%`);}const [rows]=await pool.query<RowDataPacket[]>(`SELECT c.id,c.legal_name legalName,c.display_name displayName,c.slug,c.status,c.sage_company_code sageCompanyCode,c.external_source externalSource,c.external_id externalId,l.plan_code planCode,l.max_employees maxEmployees,l.document_retention_days documentRetentionDays,COALESCE(l.financial_status,'ACTIVE') financialStatus,l.blocked_at blockedAt,l.block_reason blockReason FROM companies c LEFT JOIN company_licenses l ON l.company_id=c.id WHERE ${where} ORDER BY c.display_name LIMIT 100`,args);res.json({companies:rows,total:rows.length});});
 r.get('/companies/:id',async(req,res)=>{const [rows]=await pool.query<RowDataPacket[]>(`SELECT c.id,c.legal_name legalName,c.display_name displayName,c.slug,c.status,c.sage_company_code sageCompanyCode,c.external_source externalSource,c.external_id externalId,l.plan_code planCode,l.max_employees maxEmployees,l.document_retention_days documentRetentionDays,COALESCE(l.financial_status,'ACTIVE') financialStatus,l.blocked_at blockedAt,l.block_reason blockReason FROM companies c LEFT JOIN company_licenses l ON l.company_id=c.id WHERE c.id=? LIMIT 1`,[req.params.id]);if(!rows[0])throw notFound('Empresa PayHub não encontrada.');res.json({company:rows[0]});});
 r.post('/companies',async(req,res)=>{const b=req.body||{};const result=await provisioning.provision({legalName:val(b.legalName),displayName:val(b.displayName),slug:val(b.slug),sageCompanyCode:val(b.sageCompanyCode),master:{name:val(b.master?.name),email:val(b.master?.email),password:val(b.master?.password)},externalSource:'PONTO_CERTO',externalId:val(b.externalSubscriptionId),idempotencyKey:req.get('x-pc-idempotency-key')||null});res.status(result.alreadyProvisioned?200:201).json({company:{id:result.companyId},masterUserId:result.masterUserId,alreadyProvisioned:result.alreadyProvisioned});});
 r.put('/companies/:id/subscription',async(req,res)=>{const b=req.body||{},id=Number(req.params.id);if(!id)throw badRequest('Empresa inválida.');await pool.query(`INSERT INTO company_licenses(company_id,external_source,external_subscription_id,plan_code,max_employees,document_retention_days,financial_status,blocked_at,block_reason,created_at,updated_at) VALUES(?,'PONTO_CERTO',?,?,?,?,?,IF(?='BLOCKED',UTC_TIMESTAMP(),NULL),?,UTC_TIMESTAMP(),UTC_TIMESTAMP()) ON DUPLICATE KEY UPDATE external_subscription_id=VALUES(external_subscription_id),plan_code=VALUES(plan_code),max_employees=VALUES(max_employees),document_retention_days=VALUES(document_retention_days),financial_status=VALUES(financial_status),blocked_at=IF(VALUES(financial_status)='BLOCKED',COALESCE(blocked_at,UTC_TIMESTAMP()),NULL),block_reason=VALUES(block_reason),updated_at=UTC_TIMESTAMP()`,[id,val(b.subscriptionId)||null,val(b.planCode)||null,b.maxEmployees??null,b.documentRetentionDays??null,val(b.status)||'ACTIVE',val(b.status)||'ACTIVE',val(b.blockReason)||null]);res.json({ok:true,companyId:id});});
 r.post('/companies/:id/block',async(req,res)=>{const id=Number(req.params.id);await pool.query(`INSERT INTO company_licenses(company_id,financial_status,blocked_at,block_reason,created_at,updated_at) VALUES(?,'BLOCKED',UTC_TIMESTAMP(),?,UTC_TIMESTAMP(),UTC_TIMESTAMP()) ON DUPLICATE KEY UPDATE financial_status='BLOCKED',blocked_at=COALESCE(blocked_at,UTC_TIMESTAMP()),block_reason=VALUES(block_reason),updated_at=UTC_TIMESTAMP()`,[id,val(req.body?.reason)||'Bloqueio financeiro pelo Ponto Certo SaaS']);res.json({ok:true,companyId:id,status:'BLOCKED'});});
 r.post('/companies/:id/unblock',async(req,res)=>{const id=Number(req.params.id);await pool.query(`INSERT INTO company_licenses(company_id,financial_status,created_at,updated_at) VALUES(?,'ACTIVE',UTC_TIMESTAMP(),UTC_TIMESTAMP()) ON DUPLICATE KEY UPDATE financial_status='ACTIVE',blocked_at=NULL,block_reason=NULL,updated_at=UTC_TIMESTAMP()`,[id]);res.json({ok:true,companyId:id,status:'ACTIVE'});});
 return r;}
