import {StyleSheet,Text,View} from 'react-native';
import {money} from '../lib/format';
import {colors} from '../theme/colors';
import {Card} from './Ui';
import {StatusBadge} from './StatusBadge';
function value(data:any,...keys:string[]){for(const k of keys)if(data?.[k]!==undefined&&data?.[k]!==null)return data[k];return null;}
export function PayrollDetail({data}:{data:any}){const items=[...(data?.items??[])].sort((a,b)=>Number(a.sortOrder??0)-Number(b.sortOrder??0));const gross=value(data,'gross_amount','grossAmount','gross');const deductions=value(data,'deduction_amount','deductionAmount','deductions');const net=value(data,'net_amount','netAmount','net');return <View style={styles.root}><View style={styles.summary}><Metric label="Vencimentos" value={money(gross)}/><Metric label="Descontos" value={money(deductions)}/><Metric label="Líquido" value={money(net)} accent/></View><View style={styles.sectionHead}><Text style={styles.title}>Eventos da folha</Text>{data?.status?<StatusBadge status={data.status}/>:null}</View>{items.map((item:any,index:number)=><Card key={`${item.eventCode??item.code}-${index}`} style={styles.event}><View style={styles.eventTop}><Text style={styles.code}>{String(item.eventCode??item.code??'').padStart(4,'0')}</Text><Text style={[styles.nature,item.nature==='EARNING'?styles.earning:styles.deduction]}>{item.nature==='EARNING'?'Vencimento':'Desconto'}</Text></View><Text style={styles.description}>{item.description}</Text><View style={styles.eventBottom}><Text style={styles.reference}>Ref.: {item.referenceValue??item.reference??'—'}</Text><Text style={styles.amount}>{money(item.amount)}</Text></View></Card>)}</View>}
function Metric({label,value,accent=false}:{label:string;value:string;accent?:boolean}){return <View style={[styles.metric,accent&&styles.metricAccent]}><Text style={styles.metricLabel}>{label}</Text><Text style={[styles.metricValue,accent&&{color:colors.primary}]}>{value}</Text></View>}
const styles=StyleSheet.create({root:{gap:12},summary:{flexDirection:'row',gap:8},metric:{flex:1,backgroundColor:'#fff',borderWidth:1,borderColor:colors.border,borderRadius:14,padding:11},metricAccent:{backgroundColor:'#F2F4FF',borderColor:'#DDE2FF'},metricLabel:{fontSize:9,color:colors.muted,fontWeight:'800'},metricValue:{fontSize:13,color:colors.text,fontWeight:'900',marginTop:5},sectionHead:{flexDirection:'row',justifyContent:'space-between',alignItems:'center',marginTop:8},title:{fontSize:17,fontWeight:'900',color:colors.text},event:{borderRadius:15,padding:14,gap:7},eventTop:{flexDirection:'row',justifyContent:'space-between',alignItems:'center'},code:{fontSize:11,fontWeight:'800',color:colors.muted},nature:{fontSize:9,fontWeight:'900',paddingHorizontal:8,paddingVertical:4,borderRadius:99},earning:{backgroundColor:colors.greenSoft,color:colors.green},deduction:{backgroundColor:colors.redSoft,color:colors.red},description:{fontSize:14,fontWeight:'700',color:colors.text,lineHeight:20},eventBottom:{flexDirection:'row',justifyContent:'space-between',gap:12},reference:{fontSize:11,color:colors.muted},amount:{fontSize:14,color:colors.text,fontWeight:'900'}});
