import {forwardRef,useImperativeHandle,useRef} from 'react';
import {StyleSheet,Text,View} from 'react-native';
import {WebView} from 'react-native-webview';
import {colors} from '../theme/colors';
export type SignatureCanvasHandle={read():void;clear():void};
const html=`<!doctype html><html><head><meta name="viewport" content="width=device-width,initial-scale=1,maximum-scale=1,user-scalable=no"><style>*{box-sizing:border-box}html,body{margin:0;width:100%;height:100%;overflow:hidden;background:#fff}canvas{width:100%;height:100%;touch-action:none}</style></head><body><canvas id="c"></canvas><script>const c=document.getElementById('c'),x=c.getContext('2d');let d=false;function size(){c.width=Math.max(600,innerWidth*devicePixelRatio);c.height=Math.max(230,innerHeight*devicePixelRatio);x.scale(devicePixelRatio,devicePixelRatio);x.lineWidth=2.4;x.lineCap='round';x.strokeStyle='#16213e'}size();function p(e){const r=c.getBoundingClientRect();const t=e.touches?e.touches[0]:e;return [t.clientX-r.left,t.clientY-r.top]}function down(e){e.preventDefault();d=true;const q=p(e);x.beginPath();x.moveTo(q[0],q[1])}function move(e){if(!d)return;e.preventDefault();const q=p(e);x.lineTo(q[0],q[1]);x.stroke()}function up(e){if(!d)return;e&&e.preventDefault();d=false;window.ReactNativeWebView.postMessage(JSON.stringify({type:'changed'}))}c.addEventListener('touchstart',down,{passive:false});c.addEventListener('touchmove',move,{passive:false});c.addEventListener('touchend',up,{passive:false});c.addEventListener('mousedown',down);c.addEventListener('mousemove',move);c.addEventListener('mouseup',up);function read(){window.ReactNativeWebView.postMessage(JSON.stringify({type:'signature',data:c.toDataURL('image/png')}))}function clear(){x.clearRect(0,0,c.width,c.height);window.ReactNativeWebView.postMessage(JSON.stringify({type:'cleared'}))}</script></body></html>`;
export const SignatureCanvas=forwardRef<SignatureCanvasHandle,{onSignature(value:string):void;onChanged?(value:boolean):void}>(({onSignature,onChanged},ref)=>{const web=useRef<WebView>(null);useImperativeHandle(ref,()=>({read:()=>web.current?.injectJavaScript('read();true;'),clear:()=>web.current?.injectJavaScript('clear();true;')}));return <View><View style={styles.frame}><WebView ref={web} source={{html}} originWhitelist={['*']} scrollEnabled={false} bounces={false} onMessage={e=>{try{const m=JSON.parse(e.nativeEvent.data);if(m.type==='signature')onSignature(m.data);if(m.type==='changed')onChanged?.(true);if(m.type==='cleared')onChanged?.(false);}catch{}}}/></View><Text style={styles.help}>Assine com o dedo dentro do quadro.</Text></View>});
SignatureCanvas.displayName='SignatureCanvas';
const styles=StyleSheet.create({frame:{height:185,borderWidth:1,borderColor:colors.border,borderRadius:16,overflow:'hidden',backgroundColor:'#fff'},help:{fontSize:11,color:colors.muted,marginTop:7}});
