import {useCallback,useRef,useState} from 'react';
import {Pressable,ScrollView,StyleSheet,Text,TextInput,View} from 'react-native';
import {SafeAreaView} from 'react-native-safe-area-context';
import {router,useFocusEffect,useLocalSearchParams} from 'expo-router';
import {PayrollDetail} from '../../../components/PayrollDetail';
import {Button,ErrorBanner,Loading} from '../../../components/Ui';
import {SignatureCanvas,type SignatureCanvasHandle} from '../../../components/SignatureCanvas';
import {api} from '../../../lib/api';
import {collectSignatureEvidence} from '../../../lib/evidence';
import {colors} from '../../../theme/colors';

export default function SignScreen(){
  const{id}=useLocalSearchParams<{id:string}>();const payrollId=Number(id);const[data,setData]=useState<any|null>(null);const[loading,setLoading]=useState(true);const[busy,setBusy]=useState(false);const[error,setError]=useState('');const[accepted,setAccepted]=useState(false);const[pin,setPin]=useState('');const[drawing,setDrawing]=useState('');const[drawingChanged,setDrawingChanged]=useState(false);const canvas=useRef<SignatureCanvasHandle>(null);
  const load=useCallback(async()=>{try{const r=await api.myPayroll(payrollId);setData(r.payroll);setError('')}catch(e){setError(e instanceof Error?e.message:'Falha ao abrir holerite.')}finally{setLoading(false)}},[payrollId]);useFocusEffect(useCallback(()=>{void load()},[load]));
  const requireDraw=data?.signatureMode==='ACCEPT_AND_DRAW';
  async function submit(signatureOverride?:string){const finalDrawing=signatureOverride||drawing;if(!accepted){setError('Confirme a declaração de ciência antes de assinar.');return}if(pin.length!==6){setError('Informe seu PIN de 6 dígitos.');return}if(requireDraw&&!finalDrawing){if(drawingChanged){canvas.current?.read();return}setError('Faça sua assinatura no quadro antes de continuar.');return}setBusy(true);setError('');try{const clientEvidence=await collectSignatureEvidence();await api.signPayroll(payrollId,{pin,drawing:finalDrawing||undefined,origin:'ANDROID',clientEvidence});router.replace({pathname:'/(employee)/payroll/[id]',params:{id:String(payrollId)}})}catch(e){setError(e instanceof Error?e.message:'Falha ao assinar.')}finally{setBusy(false)}}
  if(loading)return <SafeAreaView style={{flex:1,backgroundColor:colors.bg}}><Loading label="Preparando assinatura…"/></SafeAreaView>;
  return <SafeAreaView style={styles.safe} edges={['top']}><View style={styles.header}><Button variant="ghost" style={styles.back} onPress={()=>router.back()}>‹ Voltar</Button><Text style={styles.headerTitle}>Assinar holerite</Text><View style={{width:90}}/></View><ScrollView contentContainerStyle={styles.content} keyboardShouldPersistTaps="handled">{data?<><PayrollDetail data={data}/><View style={styles.acceptBox}><Pressable style={styles.checkRow} onPress={()=>setAccepted(v=>!v)}><View style={[styles.checkbox,accepted&&styles.checkboxOn]}>{accepted?<Text style={styles.check}>✓</Text>:null}</View><Text style={styles.acceptText}>{data.acceptanceText}</Text></Pressable></View>{requireDraw?<View style={styles.section}><Text style={styles.label}>Assinatura desenhada</Text><SignatureCanvas ref={canvas} onChanged={setDrawingChanged} onSignature={value=>{setDrawing(value);void submit(value)}}/><Button variant="secondary" style={styles.clear} onPress={()=>{canvas.current?.clear();setDrawing('');setDrawingChanged(false)}}>Limpar assinatura</Button></View>:null}<View style={styles.section}><Text style={styles.label}>Confirme seu PIN de 6 dígitos</Text><TextInput style={styles.input} secureTextEntry keyboardType="number-pad" maxLength={6} value={pin} onChangeText={v=>setPin(v.replace(/\D/g,'').slice(0,6))} placeholder="••••••" placeholderTextColor="#9CA5B8"/></View><View style={styles.security}><Text style={styles.lock}>🔒</Text><Text style={styles.securityText}>Ao assinar, o PayHub registra data e hora, IP, informações técnicas do dispositivo/app, integridade do documento e, quando autorizado, localização geográfica como evidência.</Text></View><ErrorBanner message={error}/><Button disabled={busy||pin.length!==6||!accepted||(requireDraw&&!drawingChanged&&!drawing)} onPress={()=>void submit()}>{busy?'Assinando…':'Assinar eletronicamente'}</Button></>:<Text>Documento indisponível.</Text>}</ScrollView></SafeAreaView>
}
const styles=StyleSheet.create({safe:{flex:1,backgroundColor:colors.bg},header:{minHeight:66,paddingHorizontal:10,flexDirection:'row',alignItems:'center',justifyContent:'space-between',backgroundColor:'#fff',borderBottomWidth:1,borderBottomColor:colors.border},back:{width:90,minHeight:42,paddingHorizontal:4},headerTitle:{fontSize:16,fontWeight:'900',color:colors.text},content:{padding:14,paddingBottom:40},acceptBox:{backgroundColor:'#F3F5FF',borderWidth:1,borderColor:'#DDE2FF',borderRadius:16,padding:14,marginTop:18},checkRow:{flexDirection:'row',alignItems:'flex-start',gap:11},checkbox:{width:24,height:24,borderWidth:2,borderColor:'#AAB3C8',borderRadius:7,alignItems:'center',justifyContent:'center',backgroundColor:'#fff',marginTop:1},checkboxOn:{backgroundColor:colors.primary,borderColor:colors.primary},check:{color:'#fff',fontWeight:'900'},acceptText:{flex:1,fontSize:12,lineHeight:18,color:'#46516C'},section:{marginTop:18},label:{fontSize:12,fontWeight:'800',color:'#59637A',marginBottom:8},input:{height:52,borderRadius:14,borderWidth:1,borderColor:colors.border,backgroundColor:'#fff',paddingHorizontal:15,fontSize:20,letterSpacing:4,color:colors.text},clear:{marginTop:9,minHeight:42},security:{flexDirection:'row',alignItems:'flex-start',gap:9,marginVertical:18,padding:13,backgroundColor:'#EEF1F6',borderRadius:14},lock:{fontSize:15},securityText:{flex:1,fontSize:10.5,lineHeight:16,color:colors.muted}})
