import {useMemo,useState} from 'react';
import {KeyboardAvoidingView,Platform,Pressable,ScrollView,StyleSheet,Text,TextInput,View,type TextInputProps} from 'react-native';
import {SafeAreaView} from 'react-native-safe-area-context';
import {router} from 'expo-router';
import {useAuth} from '../auth/AuthProvider';
import {Brand} from '../components/Brand';
import {CompanySelector} from '../components/CompanySelector';
import {Button,ErrorBanner} from '../components/Ui';
import {ApiError} from '../lib/api';
import {cpfMask} from '../lib/format';
import {colors} from '../theme/colors';
export default function Login(){
  const{login,firstAccess,pendingSelection,selectCompany,cancelCompanySelection}=useAuth();
  const[cpf,setCpf]=useState('');const[pin,setPin]=useState('');const[confirm,setConfirm]=useState('');const[birthDate,setBirthDate]=useState('');const[first,setFirst]=useState(false);const[busy,setBusy]=useState(false);const[companyBusy,setCompanyBusy]=useState<number|null>(null);const[error,setError]=useState('');const validCpf=useMemo(()=>cpf.replace(/\D/g,'').length===11,[cpf]);
  async function submit(){if(!validCpf||pin.length!==6)return;setBusy(true);setError('');try{const state=await login(cpf,pin);if(state==='AUTHENTICATED')router.replace('/(employee)');}catch(e){if(e instanceof ApiError&&e.code==='PIN_NOT_SET'){setFirst(true);setPin('');setError('Primeiro acesso: confirme seus dados e crie seu PIN de 6 dígitos.');}else setError(e instanceof Error?e.message:'Não foi possível entrar.');}finally{setBusy(false)}}
  async function activate(){if(pin!==confirm){setError('Os PINs não conferem.');return}if(!/^\d{4}-\d{2}-\d{2}$/.test(birthDate)){setError('Informe a data no formato AAAA-MM-DD.');return}setBusy(true);setError('');try{const state=await firstAccess(cpf,birthDate,pin);if(state==='AUTHENTICATED')router.replace('/(employee)');}catch(e){setError(e instanceof Error?e.message:'Falha no primeiro acesso.')}finally{setBusy(false)}}
  async function chooseCompany(companyId:number){setCompanyBusy(companyId);setError('');try{await selectCompany(companyId);router.replace('/(employee)');}catch(e){setError(e instanceof Error?e.message:'Falha ao selecionar a empresa.');}finally{setCompanyBusy(null)}}
  if(pendingSelection)return <SafeAreaView style={styles.safe}><ScrollView contentContainerStyle={styles.selectionScroll}><View style={styles.hero}><Brand light subtitle="Gestão digital de holerites"/><Text style={styles.heroTitle}>Um CPF, cada empresa no seu próprio contexto.</Text><Text style={styles.heroText}>Escolha o vínculo que deseja consultar. Documentos, notificações e assinaturas permanecem isolados por empresa.</Text></View><View style={styles.card}><CompanySelector companies={pendingSelection.companies} busyCompanyId={companyBusy} onSelect={(id)=>void chooseCompany(id)} onCancel={()=>{cancelCompanySelection();setFirst(false);setPin('');setConfirm('');setError('');}}/><ErrorBanner message={error}/></View></ScrollView></SafeAreaView>;
  return <SafeAreaView style={styles.safe}><KeyboardAvoidingView style={{flex:1}} behavior={Platform.OS==='ios'?'padding':undefined}><ScrollView contentContainerStyle={styles.scroll} keyboardShouldPersistTaps="handled"><View style={styles.hero}><Brand light subtitle="Gestão digital de holerites"/><Text style={styles.heroTitle}>Seu holerite, seguro e na palma da mão.</Text><Text style={styles.heroText}>Visualize, assine e compartilhe seus documentos pelo app oficial do PayHub.</Text></View><View style={styles.card}><Text style={styles.eyebrow}>{first?'ATIVAÇÃO DO ACESSO':'PORTAL DO FUNCIONÁRIO'}</Text><Text style={styles.title}>{first?'Crie seu PIN':'Bem-vindo ao PayHub'}</Text><Text style={styles.subtitle}>{first?'Confirme sua data de nascimento e escolha um PIN com 6 números.':'Entre usando seu CPF e o PIN de 6 dígitos.'}</Text><Field label="CPF" value={cpf} editable={!first} placeholder="000.000.000-00" keyboardType="number-pad" maxLength={14} onChangeText={v=>setCpf(cpfMask(v))}/>{first&&<Field label="Data de nascimento" value={birthDate} placeholder="AAAA-MM-DD" keyboardType="numbers-and-punctuation" maxLength={10} onChangeText={setBirthDate}/>}<Field label={first?'Novo PIN':'PIN de 6 dígitos'} value={pin} placeholder="••••••" secureTextEntry keyboardType="number-pad" maxLength={6} onChangeText={v=>setPin(v.replace(/\D/g,'').slice(0,6))}/>{first&&<Field label="Confirmar PIN" value={confirm} placeholder="••••••" secureTextEntry keyboardType="number-pad" maxLength={6} onChangeText={v=>setConfirm(v.replace(/\D/g,'').slice(0,6))}/>}<ErrorBanner message={error}/><Button disabled={busy||!validCpf||pin.length!==6||(first&&confirm.length!==6)} onPress={()=>void(first?activate():submit())}>{busy?(first?'Ativando…':'Entrando…'):(first?'Ativar e entrar':'Entrar')}</Button>{first&&<Pressable onPress={()=>{setFirst(false);setPin('');setConfirm('');setError('')}} style={styles.back}><Text style={styles.backText}>Voltar ao login</Text></Pressable>}<View style={styles.security}><Text style={styles.securityIcon}>🔒</Text><Text style={styles.securityText}>Sessão protegida, auditoria e evidências de assinatura.</Text></View></View><Text style={styles.adminNote}>Acesso administrativo continua disponível no painel web do PayHub.</Text></ScrollView></KeyboardAvoidingView></SafeAreaView>}
function Field({label,...props}:TextInputProps&{label:string}){return <View style={styles.field}><Text style={styles.label}>{label}</Text><TextInput {...props} style={[styles.input,props.editable===false&&styles.disabledInput]} placeholderTextColor="#A2AABC" autoCapitalize="none"/></View>}
const styles=StyleSheet.create({safe:{flex:1,backgroundColor:colors.navy},scroll:{flexGrow:1,justifyContent:'center'},selectionScroll:{flexGrow:1,justifyContent:'center'},hero:{paddingHorizontal:24,paddingTop:30,paddingBottom:30,backgroundColor:colors.navy},heroTitle:{fontSize:31,lineHeight:36,fontWeight:'900',color:'#fff',marginTop:28,maxWidth:360},heroText:{fontSize:14,lineHeight:21,color:'#B8C8E7',marginTop:10,maxWidth:360},card:{backgroundColor:colors.bg,borderTopLeftRadius:30,borderTopRightRadius:30,padding:24,paddingBottom:28},eyebrow:{fontSize:10,fontWeight:'900',letterSpacing:1.5,color:colors.primary,marginBottom:7},title:{fontSize:26,fontWeight:'900',color:colors.text},subtitle:{fontSize:13,lineHeight:19,color:colors.muted,marginTop:7,marginBottom:18},field:{marginBottom:13},label:{fontSize:12,fontWeight:'800',color:'#59637A',marginBottom:7},input:{height:52,borderRadius:14,borderWidth:1,borderColor:colors.border,backgroundColor:'#fff',paddingHorizontal:15,fontSize:16,color:colors.text},disabledInput:{backgroundColor:'#EEF1F6',color:colors.muted},back:{alignSelf:'center',padding:13},backText:{color:colors.primary,fontWeight:'800'},security:{flexDirection:'row',alignItems:'center',gap:8,marginTop:18,padding:12,backgroundColor:'#EEF1FF',borderRadius:12},securityIcon:{fontSize:14},securityText:{flex:1,fontSize:11,color:'#59659A',fontWeight:'600'},adminNote:{textAlign:'center',fontSize:10,color:'#8290AE',padding:15,backgroundColor:colors.bg}});
