import { useEffect,useRef,useState,type ReactNode } from 'react';
import { useAuth } from '../auth/AuthProvider';
import { Brand } from './Brand';
import { NotificationCenter } from './NotificationCenter';
const items:Array<[string,string,string]>=[['dashboard','Visão geral','◫'],['employees','Funcionários','◎'],['groups','Grupos','◉'],['payrolls','Holerites','▤'],['users','Usuários','♙'],['integration','Integração Sage','↔'],['audit','Auditoria','◷'],['settings','Configurações','⚙']];
export function navigate(page:string){window.location.hash=`#/${page}`;}
export function AppShell({page,children}:{page:string;children:ReactNode}){
  const{principal,logout}=useAuth();const[mobileMenu,setMobileMenu]=useState(false);const mobileRef=useRef<HTMLDivElement|null>(null);
  useEffect(()=>{if(!mobileMenu)return;const outside=(event:PointerEvent)=>{if(mobileRef.current&&!mobileRef.current.contains(event.target as Node))setMobileMenu(false);};const key=(event:KeyboardEvent)=>{if(event.key==='Escape')setMobileMenu(false);};document.addEventListener('pointerdown',outside);document.addEventListener('keydown',key);return()=>{document.removeEventListener('pointerdown',outside);document.removeEventListener('keydown',key);};},[mobileMenu]);
  if(!principal||principal.kind!=='USER')return <>{children}</>;
  const allowedItems=items.filter(([key])=>principal.role==='MASTER'||!['users','audit','settings'].includes(key));
  const go=(key:string)=>{setMobileMenu(false);navigate(key);};
  return <div className="app-shell"><aside className="sidebar"><Brand/><nav>{allowedItems.map(([key,label,icon])=><button key={key} className={page===key?'active':''} onClick={()=>navigate(key)}><span>{icon}</span>{label}</button>)}</nav><div className="sidebar-foot"><div className="user-chip"><div className="avatar">{principal.name.slice(0,2).toUpperCase()}</div><div><strong>{principal.name}</strong><span>{principal.role} · {principal.companyName}</span></div></div><button className="ghost-button" onClick={()=>void logout()}>Sair</button></div></aside><main className="main-content"><div className="desktop-topbar"><div className="topbar-spacer"/><NotificationCenter/></div><div className="mobile-top" ref={mobileRef}><Brand compact/><div className="mobile-top-actions"><button className="mobile-menu-button" aria-label="Abrir navegação" aria-expanded={mobileMenu} onClick={()=>setMobileMenu((value)=>!value)}>☰ <span>Menu</span></button><NotificationCenter/><button onClick={()=>void logout()} className="ghost-button compact">Sair</button></div>{mobileMenu&&<div className="mobile-nav-popover" role="navigation" aria-label="Navegação principal">{allowedItems.map(([key,label,icon])=><button key={key} className={page===key?'active':''} onClick={()=>go(key)}><span>{icon}</span><strong>{label}</strong>{page===key&&<i>Atual</i>}</button>)}</div>}</div>{children}</main></div>;
}
