import { useEffect,useMemo,useState } from 'react';
import { api } from '../api/client';
import { currentPushSubscription,disablePushNotifications,enablePushNotifications } from '../push';
import { useAuth } from '../auth/AuthProvider';

const LABELS:Record<string,string>={PAYROLL_AVAILABLE:'Holerite disponível',SIGNATURE_COMPLETED:'Assinatura concluída',IMPORT_COMPLETED:'Importação concluída',IMPORT_FAILED:'Falhas de importação',PENDING_SIGNATURES:'Assinaturas pendentes',CONNECTOR_OFFLINE:'Conector offline',SECURITY:'Segurança',SYSTEM:'Sistema'};
function relative(raw:any){const date=new Date(raw);const diff=Date.now()-date.getTime();if(!Number.isFinite(diff))return'';if(diff<60_000)return'agora';if(diff<3_600_000)return`${Math.floor(diff/60_000)} min`;if(diff<86_400_000)return`${Math.floor(diff/3_600_000)} h`;return date.toLocaleDateString('pt-BR');}

export function NotificationCenter(){const{principal}=useAuth();const[open,setOpen]=useState(false);const[data,setData]=useState<any>({notifications:[],unreadCount:0});const[prefs,setPrefs]=useState<Record<string,boolean>>({});const[pushOn,setPushOn]=useState(false);const[msg,setMsg]=useState('');const[busy,setBusy]=useState(false);
  const categories=useMemo(()=>principal?.kind==='EMPLOYEE'?['PAYROLL_AVAILABLE','SIGNATURE_COMPLETED','SYSTEM']:principal?.role==='MASTER'?['IMPORT_COMPLETED','IMPORT_FAILED','PENDING_SIGNATURES','CONNECTOR_OFFLINE','SECURITY','SYSTEM']:['IMPORT_COMPLETED','IMPORT_FAILED','PENDING_SIGNATURES','CONNECTOR_OFFLINE','SYSTEM'],[principal]);
  async function load(){try{const [n,p,s]=await Promise.all([api.notifications(),api.notificationPreferences(),currentPushSubscription()]);setData(n);setPrefs(p.preferences??{});setPushOn(Boolean(s));}catch{}}
  useEffect(()=>{void load();const id=window.setInterval(()=>void load(),60_000);return()=>window.clearInterval(id);},[]);
  async function enable(){setBusy(true);setMsg('');try{const r=await enablePushNotifications();setPushOn(r.enabled);setMsg(r.enabled?'Notificações deste dispositivo ativadas.':r.reason??'Não foi possível ativar.');}catch(e){setMsg(e instanceof Error?e.message:'Falha ao ativar notificações.');}finally{setBusy(false);}}
  async function disable(){setBusy(true);try{await disablePushNotifications();setPushOn(false);setMsg('Notificações deste dispositivo desativadas.');}finally{setBusy(false);}}
  async function toggle(category:string,enabled:boolean){const next={...prefs,[category]:enabled};setPrefs(next);await api.updateNotificationPreferences({[category]:enabled}).catch(()=>setPrefs(prefs));}
  async function visit(n:any){if(!n.readAt){await api.markNotificationRead(n.id).catch(()=>undefined);setData((d:any)=>({...d,unreadCount:Math.max(0,d.unreadCount-1),notifications:d.notifications.map((x:any)=>x.id===n.id?{...x,readAt:new Date().toISOString()}:x)}));}if(n.url&&String(n.url).startsWith('/#/'))window.location.hash=String(n.url).slice(2);window.dispatchEvent(new CustomEvent('payhub:refresh-payrolls'));setOpen(false);}
  return <div className="notification-center"><button className="notification-bell" aria-label="Notificações" onClick={()=>setOpen(!open)}><span>🔔</span>{data.unreadCount>0&&<b>{data.unreadCount>99?'99+':data.unreadCount}</b>}</button>{open&&<div className="notification-popover"><div className="notification-head"><div><strong>Notificações</strong><span>{data.unreadCount} não lida(s)</span></div><button className="link-button" onClick={async()=>{await api.markAllNotificationsRead();await load();}}>Marcar lidas</button></div><div className="notification-list">{data.notifications?.length?data.notifications.map((n:any)=><button key={n.id} className={`notification-item ${n.readAt?'':'unread'}`} onClick={()=>void visit(n)}><span className="notification-dot"/><div><strong>{n.title}</strong><p>{n.body}</p><small>{LABELS[n.category]??n.category} · {relative(n.createdAt)}</small></div></button>):<div className="empty-state compact-empty">Tudo em dia por aqui.</div>}</div><div className="notification-settings"><div className="notification-device"><div><strong>Notificações neste dispositivo</strong><span>{pushOn?'Ativas':'Inativas'}</span></div>{pushOn?<button className="secondary-button compact" disabled={busy} onClick={()=>void disable()}>Desativar</button>:<button className="primary-button compact" disabled={busy} onClick={()=>void enable()}>Ativar</button>}</div>{categories.map((category)=><label className="notification-pref" key={category}><span>{LABELS[category]??category}</span><input type="checkbox" checked={prefs[category]??false} onChange={(e)=>void toggle(category,e.target.checked)}/></label>)}{msg&&<p className="notification-msg">{msg}</p>}</div></div>}</div>;
}
