export type PayrollItemLike={eventCode?:string|number;code?:string|number;nature?:string;description?:string;referenceValue?:string|null;reference?:string|null;amount?:number|string|null};

export function eventCodeOf(item:PayrollItemLike):string{return String(item.eventCode??item.code??'').trim();}
export function natureLabel(value:string|undefined|null):string{const nature=String(value??'').toUpperCase();if(nature==='EARNING')return'VENCIMENTOS';if(nature==='DEDUCTION')return'DESCONTOS';if(nature==='BASE')return'BASE';return'OUTROS';}
function natureRank(value:string|undefined|null):number{const nature=String(value??'').toUpperCase();if(nature==='EARNING')return 0;if(nature==='DEDUCTION')return 1;if(nature==='BASE')return 2;return 3;}
function numericCode(value:string):number{const n=Number(value.replace(/\D/g,''));return Number.isFinite(n)?n:Number.MAX_SAFE_INTEGER;}
export function sortPayrollItems<T extends PayrollItemLike>(items:T[]|undefined|null):T[]{return [...(items??[])].sort((a,b)=>natureRank(a.nature)-natureRank(b.nature)||numericCode(eventCodeOf(a))-numericCode(eventCodeOf(b))||eventCodeOf(a).localeCompare(eventCodeOf(b),'pt-BR'));}
export function brMoney(value:unknown):string{return value==null||value===''?'—':Number(value).toLocaleString('pt-BR',{minimumFractionDigits:2,maximumFractionDigits:2});}
export function padEventCode(value:string|number|undefined|null):string{const raw=String(value??'').trim();if(!/^\d+$/.test(raw))return raw||'—';return raw.length<5?raw.padStart(5,'0'):raw;}
export function monthName(month:number):string{return['Janeiro','Fevereiro','Março','Abril','Maio','Junho','Julho','Agosto','Setembro','Outubro','Novembro','Dezembro'][Math.max(0,Math.min(11,month-1))]??String(month);}
export function parseCompetence(data:any):{month:number;year:number;label:string}{if(data?.competence){const m=/^(\d{1,2})\/(\d{4})$/.exec(String(data.competence));if(m){const month=Number(m[1]);const year=Number(m[2]);return{month,year,label:`${monthName(month)}/${year}`};}}const month=Number(data?.month??0);const year=Number(data?.year??0);return{month,year,label:month&&year?`${monthName(month)}/${year}`:'—'};}
export function payrollBases(data:any){const raw=data?.rawReference??data?.raw_reference??{};const base=raw?.base??{};const items=sortPayrollItems(data?.items??[]);const salary=items.find((i)=>eventCodeOf(i)==='1'&&String(i.nature).toUpperCase()==='EARNING');const fgtsBase=numberOrNull(base.vl_base_fgts);return{salaryBase:numberOrNull(salary?.amount),inssBase:numberOrNull(base.vl_base_inss),fgtsBase,fgtsMonth:fgtsBase==null?null:Math.round(fgtsBase*8)/100,irrfBase:numberOrNull(base.vl_base_irrf),irrfBracket:0};}
function numberOrNull(value:any):number|null{if(value==null||value==='')return null;const n=Number(value);return Number.isFinite(n)?n:null;}
